#!/usr/bin/env python3
"""Generate the first low-risk RoyalNode PCB routes.

This intentionally routes only stable, low-current nets and adds the intended
top and Layer-2 ground pours. It does not route RF, high-current power rails or
switching loops.
"""

from __future__ import annotations

import re
import uuid
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PCB = ROOT / "hardware/kicad/RoyalNode/RoyalNode.kicad_pcb"
NAMESPACE = uuid.UUID("0c64c82f-b03a-455f-93ce-ceb8a0674a31")

SEGMENTS = [
    {
        "name": "e22-dio2-to-txen",
        "net": "E22_TXEN_DIO2",
        "layer": "F.Cu",
        "width": 0.20,
        "points": [(53.65, 48.92), (53.65, 46.38)],
    },
    {
        "name": "e22-vcc-local",
        "net": "5V_RADIO",
        "layer": "F.Cu",
        "width": 0.80,
        "points": [(53.65, 43.84), (53.65, 41.30)],
    },
    {
        "name": "u3-5v-radio-local",
        "net": "5V_RADIO",
        "layer": "F.Cu",
        "width": 0.20,
        "points": [(57.35, 54.25), (57.35, 55.25)],
    },
    {
        "name": "5v-radio-u3-to-e22-rotated-o",
        "net": "5V_RADIO",
        "layer": "F.Cu",
        "width": 0.20,
        "points": [(57.35, 54.25), (55.60, 54.25), (55.60, 53.00)],
    },
    {
        "name": "5v-radio-u3-to-e22-top-pour-o",
        "net": "5V_RADIO",
        "layer": "F.Cu",
        "width": 0.50,
        "points": [(55.60, 53.00), (55.60, 43.84), (53.65, 43.84)],
    },
    {
        "name": "5v-radio-output-cap-spine-p",
        "net": "5V_RADIO",
        "layer": "F.Cu",
        "width": 0.50,
        "points": [(55.60, 43.84), (55.60, 26.60), (40.48, 26.60)],
    },
    {
        "name": "5v-radio-c503-top-corridor-r",
        "net": "5V_RADIO",
        "layer": "F.Cu",
        "width": 0.50,
        "points": [(89.525, 46.00), (89.525, 42.40), (55.60, 42.40), (55.60, 43.84)],
    },
    {
        "name": "5v-radio-lower-bank-spine-q",
        "net": "5V_RADIO",
        "layer": "F.Cu",
        "width": 0.50,
        "points": [(55.60, 53.00), (55.60, 70.30), (56.53, 70.30), (56.53, 93.40)],
    },
    {
        "name": "radio-bulk-cap-bank",
        "net": "5V_RADIO",
        "layer": "F.Cu",
        "width": 0.60,
        "points": [(56.53, 93.40), (62.53, 93.40), (69.05, 93.40), (75.23, 93.40)],
    },
    {
        "name": "radio-bulk-c500-stub",
        "net": "5V_RADIO",
        "layer": "F.Cu",
        "width": 0.60,
        "points": [(56.53, 91.00), (56.53, 93.40)],
    },
    {
        "name": "radio-bulk-c501-stub",
        "net": "5V_RADIO",
        "layer": "F.Cu",
        "width": 0.60,
        "points": [(62.53, 91.00), (62.53, 93.40)],
    },
    {
        "name": "radio-bulk-c502-stub",
        "net": "5V_RADIO",
        "layer": "F.Cu",
        "width": 0.60,
        "points": [(69.05, 91.00), (69.05, 93.40)],
    },
    {
        "name": "radio-bulk-c504-c505-stub",
        "net": "5V_RADIO",
        "layer": "F.Cu",
        "width": 0.60,
        "points": [(75.23, 86.00), (75.23, 91.00), (75.23, 93.40)],
    },
    {
        "name": "u3-boost-sw-upper-local",
        "net": "BOOST_SW",
        "layer": "F.Cu",
        "width": 0.20,
        "points": [(60.65, 54.25), (60.65, 54.75)],
    },
    {
        "name": "u3-boost-sw-lower-local",
        "net": "BOOST_SW",
        "layer": "F.Cu",
        "width": 0.20,
        "points": [(60.65, 55.25), (60.65, 55.75)],
    },
    {
        "name": "boost-sw-u3-to-l2-upper",
        "net": "BOOST_SW",
        "layer": "F.Cu",
        "width": 0.40,
        "points": [(60.65, 54.75), (62.40, 54.75), (62.40, 55.00), (64.14, 55.00)],
    },
    {
        "name": "boost-sw-u3-to-l2-lower",
        "net": "BOOST_SW",
        "layer": "F.Cu",
        "width": 0.40,
        "points": [(60.65, 55.25), (62.40, 55.25), (62.40, 55.00)],
    },
    {
        "name": "boost-boot-u3-to-c406",
        "net": "BOOST_BOOT",
        "layer": "F.Cu",
        "width": 0.20,
        "points": [(60.65, 53.75), (62.50, 53.75), (62.50, 49.60), (62.13, 49.60)],
    },
    {
        "name": "boost-boot-c406-sw",
        "net": "BOOST_SW",
        "layer": "F.Cu",
        "width": 0.20,
        "points": [(63.68, 49.60), (64.60, 49.60), (64.60, 55.00), (64.14, 55.00)],
    },
    {
        "name": "boost-fsw-u3-to-r402",
        "net": "BOOST_FSW",
        "layer": "F.Cu",
        "width": 0.20,
        "points": [(60.65, 56.25), (61.45, 56.25), (61.45, 60.40), (62.08, 60.40)],
    },
    {
        "name": "boost-fsw-r402-sw",
        "net": "BOOST_SW",
        "layer": "F.Cu",
        "width": 0.20,
        "points": [(63.73, 60.40), (64.60, 60.40), (64.60, 55.00), (64.14, 55.00)],
    },
    {
        "name": "i2c-pullup-3v3-link",
        "net": "3V3",
        "layer": "F.Cu",
        "width": 0.20,
        "points": [(80.39, 33.54), (84.98, 33.00), (84.98, 35.60)],
    },
    {
        "name": "i2c-pullup-sda-fanout",
        "net": "I2C_SDA",
        "layer": "F.Cu",
        "width": 0.20,
        "points": [(86.62, 33.00), (86.62, 32.00)],
    },
    {
        "name": "i2c-pullup-sda-backbone",
        "net": "I2C_SDA",
        "layer": "B.Cu",
        "width": 0.20,
        "points": [(86.62, 32.00), (86.62, 41.40)],
    },
    {
        "name": "i2c-sda-bus-join",
        "net": "I2C_SDA",
        "layer": "B.Cu",
        "width": 0.20,
        "points": [(67.20, 41.40), (86.62, 41.40)],
    },
    {
        "name": "i2c-sda-xiao-entry",
        "net": "I2C_SDA",
        "layer": "B.Cu",
        "width": 0.20,
        "points": [(67.20, 41.40), (62.61, 33.54)],
    },
    {
        "name": "i2c-pullup-scl-fanout",
        "net": "I2C_SCL",
        "layer": "F.Cu",
        "width": 0.20,
        "points": [(86.62, 35.60), (87.60, 35.60), (87.60, 34.60)],
    },
    {
        "name": "i2c-pullup-scl-backbone",
        "net": "I2C_SCL",
        "layer": "In2.Cu",
        "width": 0.20,
        "points": [(87.60, 34.60), (87.60, 42.80)],
    },
    {
        "name": "i2c-scl-bus-join",
        "net": "I2C_SCL",
        "layer": "In2.Cu",
        "width": 0.20,
        "points": [(64.80, 42.80), (87.60, 42.80)],
    },
    {
        "name": "i2c-scl-xiao-entry",
        "net": "I2C_SCL",
        "layer": "In2.Cu",
        "width": 0.20,
        "points": [(64.80, 42.80), (64.80, 36.08), (62.61, 36.08)],
    },
    {
        "name": "j6-sda-service-fanout",
        "net": "I2C_SDA",
        "layer": "F.Cu",
        "width": 0.15,
        "points": [(95.63, 22.95), (95.63, 24.45)],
    },
    {
        "name": "j6-sda-service-backbone",
        "net": "I2C_SDA",
        "layer": "B.Cu",
        "width": 0.20,
        "points": [(95.63, 24.45), (86.62, 32.00)],
    },
    {
        "name": "j6-scl-service-fanout",
        "net": "I2C_SCL",
        "layer": "F.Cu",
        "width": 0.15,
        "points": [(96.88, 22.95), (96.88, 24.45)],
    },
    {
        "name": "j6-scl-service-backbone",
        "net": "I2C_SCL",
        "layer": "In2.Cu",
        "width": 0.20,
        "points": [(96.88, 24.45), (87.60, 34.60)],
    },
    {
        "name": "j6-3v3-service-route",
        "net": "3V3",
        "layer": "F.Cu",
        "width": 0.20,
        "points": [(93.13, 22.95), (93.13, 24.45), (90.40, 24.45), (90.40, 36.70), (84.98, 36.70), (84.98, 35.60)],
    },
    {
        "name": "r204-3v3-local-via-fanout-b",
        "net": "3V3",
        "layer": "F.Cu",
        "width": 0.15,
        "points": [(69.68, 73.20), (69.68, 72.80)],
    },
    {
        "name": "r204-3v3-spine-tie-c",
        "net": "3V3",
        "layer": "In2.Cu",
        "width": 0.15,
        "points": [(69.68, 72.80), (69.68, 91.50)],
    },
    {
        "name": "r204-3v3-right-edge-service-c",
        "net": "3V3",
        "layer": "In2.Cu",
        "width": 0.15,
        "points": [(100.00, 69.00), (100.00, 36.70), (90.40, 36.70)],
    },
    {
        "name": "bq-sda-fanout",
        "net": "I2C_SDA",
        "layer": "F.Cu",
        "width": 0.15,
        "points": [(66.00, 76.90), (66.00, 77.80), (67.20, 77.80), (67.20, 78.80)],
    },
    {
        "name": "bq-sda-backbone",
        "net": "I2C_SDA",
        "layer": "B.Cu",
        "width": 0.20,
        "points": [(67.20, 78.80), (67.20, 41.40)],
    },
    {
        "name": "bq-scl-fanout",
        "net": "I2C_SCL",
        "layer": "F.Cu",
        "width": 0.15,
        "points": [(65.60, 76.90), (65.60, 79.20), (64.80, 79.20), (64.80, 80.60)],
    },
    {
        "name": "bq-scl-backbone",
        "net": "I2C_SCL",
        "layer": "In2.Cu",
        "width": 0.20,
        "points": [(64.80, 80.60), (64.80, 42.80)],
    },
    {
        "name": "bq-prog-local-route",
        "net": "BQ_PROG",
        "layer": "F.Cu",
        "width": 0.15,
        "points": [(66.90, 75.00), (69.68, 75.00), (69.68, 76.00)],
    },
    {
        "name": "bq-int-local-route",
        "net": "BQ_INT",
        "layer": "F.Cu",
        "width": 0.15,
        "points": [(66.90, 74.60), (71.33, 74.60), (71.33, 73.20)],
    },
    {
        "name": "bq-pmid-cap-bank-bus",
        "net": "BQ_PMID",
        "layer": "F.Cu",
        "width": 0.60,
        "points": [(33.73, 75.00), (39.33, 75.00), (44.93, 75.00)],
    },
    {
        "name": "bq-vbus-cap-bank-bus",
        "net": "BQ_VBUS",
        "layer": "F.Cu",
        "width": 0.60,
        "points": [(22.53, 75.00), (28.13, 75.00)],
    },
    {
        "name": "bq-vbus-c200-stub",
        "net": "BQ_VBUS",
        "layer": "F.Cu",
        "width": 0.60,
        "points": [(22.53, 77.00), (22.53, 75.00)],
    },
    {
        "name": "bq-vbus-c201-stub",
        "net": "BQ_VBUS",
        "layer": "F.Cu",
        "width": 0.60,
        "points": [(28.13, 77.00), (28.13, 75.00)],
    },
    {
        "name": "bq-vbus-c212-bus-via-fanout",
        "net": "BQ_VBUS",
        "layer": "F.Cu",
        "width": 0.20,
        "points": [(22.53, 75.00), (21.40, 75.00)],
    },
    {
        "name": "bq-vbus-c212-bottom-jog",
        "net": "BQ_VBUS",
        "layer": "B.Cu",
        "width": 0.20,
        "points": [(21.40, 75.00), (21.40, 85.80), (22.40, 85.80)],
    },
    {
        "name": "bq-vbus-c212-pad-fanout",
        "net": "BQ_VBUS",
        "layer": "F.Cu",
        "width": 0.20,
        "points": [(22.40, 85.80), (23.23, 85.00)],
    },
    {
        "name": "bq-pmid-c202-stub",
        "net": "BQ_PMID",
        "layer": "F.Cu",
        "width": 0.60,
        "points": [(33.73, 77.00), (33.73, 75.00)],
    },
    {
        "name": "bq-pmid-c203-stub",
        "net": "BQ_PMID",
        "layer": "F.Cu",
        "width": 0.60,
        "points": [(39.33, 77.00), (39.33, 75.00)],
    },
    {
        "name": "bq-pmid-c204-stub",
        "net": "BQ_PMID",
        "layer": "F.Cu",
        "width": 0.60,
        "points": [(44.93, 77.00), (44.93, 75.00)],
    },
    {
        "name": "bq-pmid-c213-bus-via-fanout",
        "net": "BQ_PMID",
        "layer": "F.Cu",
        "width": 0.20,
        "points": [(33.73, 75.00), (32.60, 75.00)],
    },
    {
        "name": "bq-pmid-c213-bottom-jog",
        "net": "BQ_PMID",
        "layer": "B.Cu",
        "width": 0.20,
        "points": [(32.60, 75.00), (27.60, 75.00), (27.60, 85.80)],
    },
    {
        "name": "bq-pmid-c213-pad-fanout",
        "net": "BQ_PMID",
        "layer": "F.Cu",
        "width": 0.20,
        "points": [(27.60, 85.80), (28.83, 85.00)],
    },
    {
        "name": "bq-pmid-u1-lower-escape-f",
        "net": "BQ_PMID",
        "layer": "F.Cu",
        "width": 0.15,
        "points": [(64.10, 73.275), (64.00, 72.45)],
    },
    {
        "name": "bq-pmid-inner-route-f",
        "net": "BQ_PMID",
        "layer": "B.Cu",
        "width": 0.30,
        "points": [(64.00, 72.45), (64.00, 71.50), (45.50, 71.50)],
    },
    {
        "name": "bq-pmid-capbus-entry-f",
        "net": "BQ_PMID",
        "layer": "F.Cu",
        "width": 0.25,
        "points": [(45.50, 71.50), (45.50, 75.00), (44.93, 75.00)],
    },
    {
        "name": "bq-sys-cap-bank-bus",
        "net": "BQ_SYS",
        "layer": "F.Cu",
        "width": 0.60,
        "points": [(22.53, 83.40), (28.13, 83.40), (33.73, 83.40), (39.33, 83.40)],
    },
    {
        "name": "bq-sys-c206-stub",
        "net": "BQ_SYS",
        "layer": "F.Cu",
        "width": 0.60,
        "points": [(22.53, 81.00), (22.53, 83.40)],
    },
    {
        "name": "bq-sys-c207-stub",
        "net": "BQ_SYS",
        "layer": "F.Cu",
        "width": 0.60,
        "points": [(28.13, 81.00), (28.13, 83.40)],
    },
    {
        "name": "bq-sys-c208-stub",
        "net": "BQ_SYS",
        "layer": "F.Cu",
        "width": 0.60,
        "points": [(33.73, 81.00), (33.73, 83.40)],
    },
    {
        "name": "bq-sys-c209-stub",
        "net": "BQ_SYS",
        "layer": "F.Cu",
        "width": 0.60,
        "points": [(39.33, 81.00), (39.33, 83.40)],
    },
    {
        "name": "bq-sys-c214-stub",
        "net": "BQ_SYS",
        "layer": "F.Cu",
        "width": 0.60,
        "points": [(34.43, 85.00), (34.43, 83.40)],
    },
    {
        "name": "bq-sys-c205-bus-via-fanout",
        "net": "BQ_SYS",
        "layer": "F.Cu",
        "width": 0.30,
        "points": [(39.33, 83.40), (40.50, 83.40)],
    },
    {
        "name": "bq-sys-c205-bottom-jog",
        "net": "BQ_SYS",
        "layer": "B.Cu",
        "width": 0.30,
        "points": [(40.50, 83.40), (40.50, 79.00), (50.00, 79.00), (50.00, 77.80)],
    },
    {
        "name": "bq-sys-c205-pad-fanout",
        "net": "BQ_SYS",
        "layer": "F.Cu",
        "width": 0.30,
        "points": [(50.00, 77.80), (50.53, 77.00)],
    },
    {
        "name": "bq-sys-cap-bank-to-u1-b",
        "net": "BQ_SYS",
        "layer": "In1.Cu",
        "width": 0.40,
        "points": [(50.00, 77.80), (54.80, 77.80), (54.80, 71.80), (65.80, 71.80)],
    },
    {
        "name": "bq-sys-u1-entry-b",
        "net": "BQ_SYS",
        "layer": "F.Cu",
        "width": 0.25,
        "points": [(65.80, 71.80), (65.90, 73.30)],
    },
    {
        "name": "bq-sys-l2-fanout-to-spine-b",
        "net": "BQ_SYS",
        "layer": "F.Cu",
        "width": 0.60,
        "points": [(68.86, 55.00), (70.50, 55.00)],
    },
    {
        "name": "bq-sys-l2-to-u1-spine-b",
        "net": "BQ_SYS",
        "layer": "In2.Cu",
        "width": 0.60,
        "points": [(70.50, 55.00), (70.50, 71.80), (65.80, 71.80)],
    },
    {
        "name": "bq-sys-u3-vin-fanout-b",
        "net": "BQ_SYS",
        "layer": "F.Cu",
        "width": 0.30,
        "points": [(60.65, 53.25), (61.20, 53.25), (61.20, 52.90)],
    },
    {
        "name": "bq-sys-u3-to-l2-spine-b",
        "net": "BQ_SYS",
        "layer": "In1.Cu",
        "width": 0.50,
        "points": [(61.20, 52.90), (70.50, 52.90), (70.50, 55.00)],
    },
    {
        "name": "bat-raw-cap-bank-bus",
        "net": "BAT_RAW",
        "layer": "F.Cu",
        "width": 0.60,
        "points": [(44.93, 83.40), (50.53, 83.40)],
    },
    {
        "name": "bat-raw-c210-stub",
        "net": "BAT_RAW",
        "layer": "F.Cu",
        "width": 0.60,
        "points": [(44.93, 81.00), (44.93, 83.40)],
    },
    {
        "name": "bat-raw-c211-stub",
        "net": "BAT_RAW",
        "layer": "F.Cu",
        "width": 0.60,
        "points": [(50.53, 81.00), (50.53, 83.40)],
    },
    {
        "name": "bat-raw-r202-to-cap-bus-branch",
        "net": "BAT_RAW",
        "layer": "F.Cu",
        "width": 0.25,
        "points": [(39.98, 89.00), (39.98, 88.00), (43.80, 88.00), (43.80, 83.40), (44.93, 83.40)],
    },
    {
        "name": "boost-input-c400-c401-local-bus",
        "net": "BQ_SYS",
        "layer": "F.Cu",
        "width": 0.40,
        "points": [(68.53, 62.80), (68.53, 66.60)],
    },
    {
        "name": "boost-input-c404-top-edge-bridge",
        "net": "BQ_SYS",
        "layer": "F.Cu",
        "width": 0.25,
        "points": [(68.86, 55.00), (68.86, 60.20), (70.73, 60.20)],
    },
    {
        "name": "boost-input-c404-pad-fanout",
        "net": "BQ_SYS",
        "layer": "F.Cu",
        "width": 0.30,
        "points": [(70.73, 60.20), (68.53, 62.80)],
    },
    {
        "name": "boost-output-c402-c403-local-bus",
        "net": "5V_RADIO",
        "layer": "F.Cu",
        "width": 0.40,
        "points": [(34.23, 24.50), (34.23, 22.50), (39.83, 22.50), (39.83, 24.50)],
    },
    {
        "name": "boost-output-r400-sense-to-cap-bus",
        "net": "5V_RADIO",
        "layer": "F.Cu",
        "width": 0.20,
        "points": [(39.83, 24.50), (39.83, 26.60), (40.48, 26.60), (40.48, 29.00)],
    },
    {
        "name": "charge-led-k-local",
        "net": "CHG_LED_K",
        "layer": "F.Cu",
        "width": 0.20,
        "points": [(35.99, 93.00), (39.98, 93.00)],
    },
    {
        "name": "d1-3v3-fanout",
        "net": "3V3",
        "layer": "F.Cu",
        "width": 0.15,
        "points": [(34.41, 93.00), (33.50, 93.00), (33.50, 91.50)],
    },
    {
        "name": "d1-3v3-internal-route",
        "net": "3V3",
        "layer": "In2.Cu",
        "width": 0.15,
        "points": [(33.50, 91.50), (100.00, 91.50), (100.00, 69.00)],
    },
    {
        "name": "bq-stat-r207-fanout",
        "net": "BQ_STAT",
        "layer": "F.Cu",
        "width": 0.20,
        "points": [(41.62, 93.00), (42.60, 93.00)],
    },
    {
        "name": "bq-stat-backbone",
        "net": "BQ_STAT",
        "layer": "In2.Cu",
        "width": 0.20,
        "points": [(42.60, 93.00), (42.60, 95.00), (16.00, 95.00), (16.00, 72.50), (62.40, 72.50), (62.40, 73.40)],
    },
    {
        "name": "bq-stat-u1-entry",
        "net": "BQ_STAT",
        "layer": "F.Cu",
        "width": 0.15,
        "points": [(62.40, 73.40), (63.10, 73.40)],
    },
    {
        "name": "bq-btst1-c216-local",
        "net": "BQ_BTST1",
        "layer": "F.Cu",
        "width": 0.15,
        "points": [(63.10, 74.60), (61.20, 74.60), (61.20, 70.50), (62.33, 70.50)],
    },
    {
        "name": "bq-btst2-u1-to-c217-k",
        "net": "BQ_BTST2",
        "layer": "F.Cu",
        "width": 0.15,
        "points": [(66.86, 75.40), (68.56, 75.40), (68.56, 78.60), (72.03, 78.60), (72.03, 82.00)],
    },
    {
        "name": "bq-sw1-c216-local",
        "net": "BQ_SW1",
        "layer": "F.Cu",
        "width": 0.20,
        "points": [(64.55, 73.30), (64.55, 70.50), (63.88, 70.50)],
    },
    {
        "name": "bq-sw1-c216-to-l1-left-wrap-e",
        "net": "BQ_SW1",
        "layer": "F.Cu",
        "width": 0.35,
        "points": [(64.55, 70.50), (64.55, 69.45), (59.00, 69.45), (59.00, 84.00), (62.59, 84.00)],
    },
    {
        "name": "bq-sw2-l1-c217-local-b",
        "net": "BQ_SW2",
        "layer": "F.Cu",
        "width": 0.40,
        "points": [(73.58, 82.00), (75.20, 82.00), (75.20, 84.00), (67.41, 84.00)],
    },
    {
        "name": "bq-ts-divider-local",
        "net": "BQ_TS",
        "layer": "F.Cu",
        "width": 0.20,
        "points": [(30.43, 89.00), (34.38, 89.00)],
    },
    {
        "name": "bq-ts-bottom-route",
        "net": "BQ_TS",
        "layer": "In2.Cu",
        "width": 0.20,
        "points": [(34.38, 87.80), (68.00, 87.80), (68.00, 76.60)],
    },
    {
        "name": "bq-ts-divider-via-fanout",
        "net": "BQ_TS",
        "layer": "F.Cu",
        "width": 0.20,
        "points": [(34.38, 89.00), (34.38, 87.80)],
    },
    {
        "name": "bq-ts-u1-fanout",
        "net": "BQ_TS",
        "layer": "F.Cu",
        "width": 0.15,
        "points": [(68.00, 76.60), (66.85, 76.60)],
    },
    {
        "name": "batp-kelvin-u1-fanout-e",
        "net": "BATP_KELVIN",
        "layer": "F.Cu",
        "width": 0.15,
        "points": [(66.875, 75.80), (67.75, 75.80), (67.75, 75.90)],
    },
    {
        "name": "batp-kelvin-bottom-escape-e",
        "net": "BATP_KELVIN",
        "layer": "B.Cu",
        "width": 0.15,
        "points": [(67.75, 75.90), (67.75, 76.05), (69.00, 76.05), (69.00, 81.30), (52.00, 81.30), (52.00, 80.20), (49.00, 80.20)],
    },
    {
        "name": "batp-kelvin-inner-route-e",
        "net": "BATP_KELVIN",
        "layer": "In2.Cu",
        "width": 0.15,
        "points": [(49.00, 80.20), (33.00, 80.20), (33.00, 90.50), (42.45, 90.50)],
    },
    {
        "name": "batp-kelvin-r202-fanout-e",
        "net": "BATP_KELVIN",
        "layer": "F.Cu",
        "width": 0.15,
        "points": [(42.45, 90.50), (42.45, 89.00), (41.625, 89.00)],
    },
    {
        "name": "bq-sdrv-c218-local",
        "net": "BQ_SDRV",
        "layer": "F.Cu",
        "width": 0.15,
        "points": [(66.86, 73.40), (68.42, 73.40), (68.42, 71.20)],
    },
    {
        "name": "bq-regn-r200-c215-local-link",
        "net": "BQ_REGN",
        "layer": "F.Cu",
        "width": 0.20,
        "points": [(28.78, 89.00), (28.78, 87.10), (39.85, 87.10), (39.85, 85.00)],
    },
    {
        "name": "bq-regn-c215-u1-pad5-fanout-a",
        "net": "BQ_REGN",
        "layer": "F.Cu",
        "width": 0.15,
        "points": [(63.10, 75.00), (62.10, 75.00), (62.10, 76.00), (60.80, 76.00)],
    },
    {
        "name": "bq-regn-c215-u1-route-a",
        "net": "BQ_REGN",
        "layer": "B.Cu",
        "width": 0.20,
        "points": [(60.80, 76.00), (39.85, 76.00), (39.85, 85.00)],
    },
    {
        "name": "bq-regn-ilim-top-bridge-b",
        "net": "BQ_REGN",
        "layer": "F.Cu",
        "width": 0.15,
        "points": [(66.85, 76.20), (65.85, 76.20), (65.85, 75.60), (63.80, 75.60), (63.80, 75.00), (63.10, 75.00)],
    },
    {
        "name": "uv-divider-local",
        "net": "UV_NODE",
        "layer": "F.Cu",
        "width": 0.20,
        "points": [(69.03, 45.20), (70.78, 45.20)],
    },
    {
        "name": "uv-node-u4-local",
        "net": "UV_NODE",
        "layer": "F.Cu",
        "width": 0.15,
        "points": [(69.03, 45.20), (69.03, 49.68), (72.86, 49.68)],
    },
    {
        "name": "ov-divider-local",
        "net": "OV_NODE",
        "layer": "F.Cu",
        "width": 0.20,
        "points": [(72.43, 45.20), (74.18, 45.20)],
    },
    {
        "name": "ov-node-u4-local",
        "net": "OV_NODE",
        "layer": "F.Cu",
        "width": 0.15,
        "points": [(74.18, 45.20), (74.18, 50.33), (72.86, 50.33)],
    },
    {
        "name": "u2-gnd-local",
        "net": "GND",
        "layer": "F.Cu",
        "width": 0.20,
        "points": [(83.16, 49.00), (84.84, 49.00)],
    },
    {
        "name": "u2-xiao-bat-iso-local",
        "net": "XIAO_BAT_ISO",
        "layer": "F.Cu",
        "width": 0.20,
        "points": [(83.16, 49.65), (82.40, 49.65), (82.40, 50.30), (85.60, 50.30), (85.60, 48.35), (84.84, 48.35)],
    },
    {
        "name": "j3-xiao-bat-iso-service-route",
        "net": "XIAO_BAT_ISO",
        "layer": "B.Cu",
        "width": 0.30,
        "points": [(85.60, 50.30), (102.40, 50.30), (102.40, 87.80), (94.38, 87.80)],
    },
    {
        "name": "j3-xiao-bat-iso-pad-entry",
        "net": "XIAO_BAT_ISO",
        "layer": "F.Cu",
        "width": 0.30,
        "points": [(94.38, 87.80), (94.38, 89.15)],
    },
    {
        "name": "j4-ntc-sense-service-route",
        "net": "NTC_SENSE",
        "layer": "B.Cu",
        "width": 0.20,
        "points": [(36.03, 89.00), (36.03, 93.60), (83.88, 93.60), (83.88, 86.65)],
    },
    {
        "name": "solar-raw-xt30-to-fuse",
        "net": "SOLAR_RAW",
        "layer": "F.Cu",
        "width": 0.80,
        "points": [(90.50, 57.00), (85.60, 57.00), (85.60, 54.00)],
    },
    {
        "name": "q1-solar-prot-gate-local",
        "net": "SOLAR_PROT_GATE",
        "layer": "F.Cu",
        "width": 0.20,
        "points": [(75.38, 55.37), (74.20, 55.37), (74.20, 57.91), (75.38, 57.91)],
    },
    {
        "name": "solar-prot-gate-u4-fanout-b",
        "net": "SOLAR_PROT_GATE",
        "layer": "F.Cu",
        "width": 0.20,
        "points": [(75.14, 49.03), (76.60, 49.03)],
    },
    {
        "name": "solar-prot-gate-backbone-b",
        "net": "SOLAR_PROT_GATE",
        "layer": "B.Cu",
        "width": 0.20,
        "points": [(76.60, 49.03), (74.00, 49.03), (74.00, 55.37)],
    },
    {
        "name": "solar-prot-gate-q1-entry-b",
        "net": "SOLAR_PROT_GATE",
        "layer": "F.Cu",
        "width": 0.20,
        "points": [(74.00, 55.37), (74.20, 55.37)],
    },
    {
        "name": "q1-solar-prot-common-left-fanout",
        "net": "SOLAR_PROT_COMMON",
        "layer": "F.Cu",
        "width": 0.40,
        "points": [(75.38, 54.10), (72.50, 54.10)],
    },
    {
        "name": "q1-solar-prot-common-backbone",
        "net": "SOLAR_PROT_COMMON",
        "layer": "B.Cu",
        "width": 0.40,
        "points": [(72.50, 54.10), (72.50, 58.50), (82.00, 58.50), (82.00, 56.64)],
    },
    {
        "name": "q1-solar-prot-common-right-entry",
        "net": "SOLAR_PROT_COMMON",
        "layer": "F.Cu",
        "width": 0.40,
        "points": [(82.00, 56.64), (80.63, 56.64)],
    },
    {
        "name": "q2-acdrv1-gate-local",
        "net": "BQ_ACDRV1",
        "layer": "F.Cu",
        "width": 0.20,
        "points": [(75.38, 63.37), (74.20, 63.37), (74.20, 65.91), (75.38, 65.91)],
    },
    {
        "name": "q2-acdrv1-u1-fanout-b",
        "net": "BQ_ACDRV1",
        "layer": "F.Cu",
        "width": 0.15,
        "points": [(64.40, 76.90), (64.40, 78.40), (63.20, 78.40)],
    },
    {
        "name": "q2-acdrv1-bottom-route-b",
        "net": "BQ_ACDRV1",
        "layer": "In1.Cu",
        "width": 0.15,
        "points": [(63.20, 78.40), (63.20, 82.40), (73.50, 82.40), (73.50, 64.80)],
    },
    {
        "name": "q2-acdrv1-gate-entry-b",
        "net": "BQ_ACDRV1",
        "layer": "F.Cu",
        "width": 0.15,
        "points": [(73.50, 64.80), (74.20, 64.80), (74.20, 65.91)],
    },
    {
        "name": "q3-acdrv2-gate-local",
        "net": "BQ_ACDRV2",
        "layer": "F.Cu",
        "width": 0.20,
        "points": [(75.38, 71.37), (74.20, 71.37), (74.20, 73.91), (75.38, 73.91)],
    },
    {
        "name": "q3-acdrv2-u1-fanout-b",
        "net": "BQ_ACDRV2",
        "layer": "F.Cu",
        "width": 0.15,
        "points": [(64.00, 76.90), (64.00, 77.60), (61.60, 77.60)],
    },
    {
        "name": "q3-acdrv2-internal-route-b",
        "net": "BQ_ACDRV2",
        "layer": "In1.Cu",
        "width": 0.15,
        "points": [(61.60, 77.60), (61.60, 84.80), (74.20, 84.80), (74.20, 72.10)],
    },
    {
        "name": "q3-acdrv2-gate-entry-b",
        "net": "BQ_ACDRV2",
        "layer": "F.Cu",
        "width": 0.15,
        "points": [(74.20, 72.10), (74.20, 73.91)],
    },
    {
        "name": "q1-solar-fused-drain-local",
        "net": "SOLAR_FUSED",
        "layer": "F.Cu",
        "width": 0.60,
        "points": [(80.63, 54.10), (80.63, 55.37)],
    },
    {
        "name": "solar-fused-fuse-fanout",
        "net": "SOLAR_FUSED",
        "layer": "F.Cu",
        "width": 0.80,
        "points": [(88.40, 54.00), (89.60, 54.00)],
    },
    {
        "name": "solar-fused-backbone",
        "net": "SOLAR_FUSED",
        "layer": "B.Cu",
        "width": 0.80,
        "points": [(89.60, 54.00), (89.60, 52.20), (80.63, 52.20)],
    },
    {
        "name": "solar-fused-q1-entry",
        "net": "SOLAR_FUSED",
        "layer": "F.Cu",
        "width": 0.80,
        "points": [(80.63, 52.20), (80.63, 54.10)],
    },
    {
        "name": "solar-fused-u4-fanout",
        "net": "SOLAR_FUSED",
        "layer": "F.Cu",
        "width": 0.20,
        "points": [(72.86, 49.03), (71.80, 49.03)],
    },
    {
        "name": "solar-fused-u4-to-backbone",
        "net": "SOLAR_FUSED",
        "layer": "B.Cu",
        "width": 0.30,
        "points": [(71.80, 49.03), (71.80, 47.80), (80.63, 47.80), (80.63, 52.20)],
    },
    {
        "name": "solar-fused-divider-r100-fanout",
        "net": "SOLAR_FUSED",
        "layer": "F.Cu",
        "width": 0.20,
        "points": [(67.38, 45.20), (66.30, 45.20), (66.30, 43.80)],
    },
    {
        "name": "solar-fused-r100-to-u4-backbone",
        "net": "SOLAR_FUSED",
        "layer": "In2.Cu",
        "width": 0.20,
        "points": [(66.30, 43.80), (71.80, 43.80), (71.80, 49.03)],
    },
    {
        "name": "solar-fused-shdn-pullup-local",
        "net": "SOLAR_FUSED",
        "layer": "F.Cu",
        "width": 0.20,
        "points": [(77.58, 47.40), (77.58, 47.80)],
    },
    {
        "name": "ltc-shdn-u4-local",
        "net": "LTC_SHDN",
        "layer": "F.Cu",
        "width": 0.15,
        "points": [(79.23, 47.40), (79.23, 51.60), (75.14, 51.60), (75.14, 50.98)],
    },
    {
        "name": "q2-solar-protected-drain-local",
        "net": "SOLAR_PROTECTED",
        "layer": "F.Cu",
        "width": 0.60,
        "points": [(80.63, 62.10), (80.63, 63.37)],
    },
    {
        "name": "q2-solar-selector-common-left-fanout-b",
        "net": "BQ_SOLAR_SELECTOR_COMMON",
        "layer": "F.Cu",
        "width": 0.40,
        "points": [(75.38, 62.10), (72.50, 62.10)],
    },
    {
        "name": "q2-solar-selector-common-backbone-b",
        "net": "BQ_SOLAR_SELECTOR_COMMON",
        "layer": "B.Cu",
        "width": 0.40,
        "points": [(72.50, 62.10), (72.50, 66.50), (82.00, 66.50), (82.00, 64.64)],
    },
    {
        "name": "q2-solar-selector-common-right-entry-b",
        "net": "BQ_SOLAR_SELECTOR_COMMON",
        "layer": "F.Cu",
        "width": 0.40,
        "points": [(82.00, 64.64), (80.63, 64.64)],
    },
    {
        "name": "solar-protected-q1-to-q2",
        "net": "SOLAR_PROTECTED",
        "layer": "F.Cu",
        "width": 0.80,
        "points": [(80.63, 57.91), (80.63, 62.10)],
    },
    {
        "name": "solar-protected-q1-left-to-right-b",
        "net": "SOLAR_PROTECTED",
        "layer": "In2.Cu",
        "width": 0.50,
        "points": [(75.38, 56.64), (75.38, 61.70), (80.63, 61.70)],
    },
    {
        "name": "solar-protected-u4-to-q1-sense-b",
        "net": "SOLAR_PROTECTED",
        "layer": "In2.Cu",
        "width": 0.25,
        "points": [(76.10, 49.68), (71.50, 49.68), (71.50, 56.64), (75.38, 56.64)],
    },
    {
        "name": "solar-protected-u4-sense-fanout-b",
        "net": "SOLAR_PROTECTED",
        "layer": "F.Cu",
        "width": 0.15,
        "points": [(75.14, 49.68), (76.10, 49.68)],
    },
    {
        "name": "q3-usb-vbus-raw-drain-local",
        "net": "USB_VBUS_RAW",
        "layer": "F.Cu",
        "width": 0.60,
        "points": [(80.63, 70.10), (80.63, 71.37)],
    },
    {
        "name": "usb-vbus-raw-mod1-to-q3-top-edge-f",
        "net": "USB_VBUS_RAW",
        "layer": "F.Cu",
        "width": 0.40,
        "points": [(80.39, 36.08), (80.39, 37.40), (103.20, 37.40), (103.20, 70.10), (80.63, 70.10)],
    },
    {
        "name": "q3-usb-selector-common-left-fanout-b",
        "net": "BQ_USB_SELECTOR_COMMON",
        "layer": "F.Cu",
        "width": 0.40,
        "points": [(75.38, 70.10), (72.50, 70.10)],
    },
    {
        "name": "q3-usb-selector-common-backbone-b",
        "net": "BQ_USB_SELECTOR_COMMON",
        "layer": "B.Cu",
        "width": 0.40,
        "points": [(72.50, 70.10), (72.50, 74.50), (82.00, 74.50), (82.00, 72.64)],
    },
    {
        "name": "q3-usb-selector-common-right-entry-b",
        "net": "BQ_USB_SELECTOR_COMMON",
        "layer": "F.Cu",
        "width": 0.40,
        "points": [(82.00, 72.64), (80.63, 72.64)],
    },
    {
        "name": "bq-vbus-q2-right-fanout",
        "net": "BQ_VBUS",
        "layer": "F.Cu",
        "width": 0.60,
        "points": [(80.63, 65.91), (83.50, 65.91)],
    },
    {
        "name": "bq-vbus-q2-q3-backbone",
        "net": "BQ_VBUS",
        "layer": "B.Cu",
        "width": 0.60,
        "points": [(83.50, 65.91), (83.50, 73.91)],
    },
    {
        "name": "bq-vbus-q2-left-to-right-b",
        "net": "BQ_VBUS",
        "layer": "In2.Cu",
        "width": 0.50,
        "points": [(75.38, 64.64), (75.38, 68.30), (83.50, 68.30), (83.50, 65.91)],
    },
    {
        "name": "bq-vbus-q3-right-entry",
        "net": "BQ_VBUS",
        "layer": "F.Cu",
        "width": 0.60,
        "points": [(83.50, 73.91), (80.63, 73.91)],
    },
    {
        "name": "bq-vbus-q3-left-to-right-b",
        "net": "BQ_VBUS",
        "layer": "In2.Cu",
        "width": 0.50,
        "points": [(75.38, 72.64), (75.38, 76.30), (83.50, 76.30), (83.50, 73.91)],
    },
    {
        "name": "u1-bq-vbus-local",
        "net": "BQ_VBUS",
        "layer": "F.Cu",
        "width": 0.15,
        "points": [(63.10, 73.80), (63.10, 74.20)],
    },
    {
        "name": "bq-vbus-u1-to-capbank-fanout-x",
        "net": "BQ_VBUS",
        "layer": "F.Cu",
        "width": 0.15,
        "points": [(63.10, 74.20), (62.05, 74.20), (62.05, 74.10)],
    },
    {
        "name": "bq-vbus-u1-to-capbank-back-x",
        "net": "BQ_VBUS",
        "layer": "B.Cu",
        "width": 0.20,
        "points": [(62.05, 74.10), (21.40, 74.10), (21.40, 75.00)],
    },
    {
        "name": "u1-bat-raw-local",
        "net": "BAT_RAW",
        "layer": "F.Cu",
        "width": 0.15,
        "points": [(66.90, 73.80), (66.90, 74.20)],
    },
    {
        "name": "bat-raw-j2-to-u2-branch-b",
        "net": "BAT_RAW",
        "layer": "In2.Cu",
        "width": 0.50,
        "points": [(90.50, 73.00), (90.50, 75.00), (86.00, 75.00), (86.00, 52.00), (87.20, 52.00), (87.20, 47.60), (82.00, 47.60)],
    },
    {
        "name": "bat-raw-u2-entry-b",
        "net": "BAT_RAW",
        "layer": "F.Cu",
        "width": 0.25,
        "points": [(82.00, 47.60), (83.16, 48.35)],
    },
    {
        "name": "bat-raw-branch-to-cap-bus-b",
        "net": "BAT_RAW",
        "layer": "In2.Cu",
        "width": 0.50,
        "points": [(86.00, 75.00), (86.00, 82.00)],
    },
    {
        "name": "bat-raw-cap-bus-backbone-b",
        "net": "BAT_RAW",
        "layer": "B.Cu",
        "width": 0.50,
        "points": [(86.00, 82.00), (50.53, 82.00), (50.53, 81.00)],
    },
    {
        "name": "bat-raw-cap-bus-to-u1-b",
        "net": "BAT_RAW",
        "layer": "In1.Cu",
        "width": 0.40,
        "points": [(50.53, 81.00), (58.00, 81.00), (58.00, 75.20), (68.00, 75.20), (68.00, 74.00)],
    },
    {
        "name": "bat-raw-u1-entry-b",
        "net": "BAT_RAW",
        "layer": "F.Cu",
        "width": 0.25,
        "points": [(68.00, 74.00), (66.90, 74.00)],
    },
    {
        "name": "boost-fb-r400-r401-local-link",
        "net": "BOOST_FB",
        "layer": "F.Cu",
        "width": 0.20,
        "points": [(42.13, 29.00), (46.08, 29.00)],
    },
    {
        "name": "boost-fb-u3-fanout-b",
        "net": "BOOST_FB",
        "layer": "F.Cu",
        "width": 0.15,
        "points": [(57.35, 55.75), (56.60, 55.75), (56.60, 55.55)],
    },
    {
        "name": "boost-fb-internal-sense-route-b",
        "net": "BOOST_FB",
        "layer": "In1.Cu",
        "width": 0.15,
        "points": [(56.60, 55.55), (56.60, 52.60), (55.20, 52.60), (55.20, 36.00), (42.13, 36.00), (42.13, 30.00)],
    },
    {
        "name": "boost-fb-r400-entry-b",
        "net": "BOOST_FB",
        "layer": "F.Cu",
        "width": 0.15,
        "points": [(42.13, 30.00), (42.13, 29.00)],
    },
    {
        "name": "boost-comp-u3-r404-local-g",
        "net": "BOOST_COMP",
        "layer": "F.Cu",
        "width": 0.15,
        "points": [(57.35, 56.25), (56.70, 56.25), (56.70, 62.80), (59.38, 62.80)],
    },
    {
        "name": "boost-comp-rc-r404-fanout",
        "net": "BOOST_COMP_RC",
        "layer": "F.Cu",
        "width": 0.20,
        "points": [(61.03, 62.80), (62.83, 62.80)],
    },
    {
        "name": "boost-ilim-u3-fanout",
        "net": "BOOST_ILIM",
        "layer": "F.Cu",
        "width": 0.15,
        "points": [(57.35, 56.75), (57.35, 61.20)],
    },
    {
        "name": "boost-ilim-internal-run",
        "net": "BOOST_ILIM",
        "layer": "F.Cu",
        "width": 0.15,
        "points": [(57.35, 61.20), (57.58, 61.20)],
    },
    {
        "name": "boost-ss-c407-local",
        "net": "BOOST_SS",
        "layer": "F.Cu",
        "width": 0.15,
        "points": [(59.75, 52.85), (59.76, 51.30)],
    },
    {
        "name": "boost-en-u3-fanout-b",
        "net": "BOOST_EN",
        "layer": "F.Cu",
        "width": 0.15,
        "points": [(60.65, 56.75), (60.65, 58.50)],
    },
    {
        "name": "boost-en-xiao-internal-route-b",
        "net": "BOOST_EN",
        "layer": "In1.Cu",
        "width": 0.15,
        "points": [(60.65, 58.50), (60.65, 60.50), (84.00, 60.50), (84.00, 23.38)],
    },
    {
        "name": "boost-en-xiao-entry-b",
        "net": "BOOST_EN",
        "layer": "F.Cu",
        "width": 0.15,
        "points": [(84.00, 23.38), (80.39, 23.38)],
    },
    {
        "name": "boost-en-r405-fanout-b",
        "net": "BOOST_EN",
        "layer": "F.Cu",
        "width": 0.15,
        "points": [(21.18, 47.00), (21.18, 48.20)],
    },
    {
        "name": "boost-en-r405-internal-route-b",
        "net": "BOOST_EN",
        "layer": "In1.Cu",
        "width": 0.15,
        "points": [(21.18, 48.20), (21.18, 28.00), (60.65, 28.00), (60.65, 58.50)],
    },
    {
        "name": "e22-nrst-fanout",
        "net": "E22_NRST",
        "layer": "F.Cu",
        "width": 0.20,
        "points": [(30.35, 46.38), (24.80, 46.38)],
    },
    {
        "name": "e22-nrst-backbone",
        "net": "E22_NRST",
        "layer": "In2.Cu",
        "width": 0.20,
        "points": [(24.80, 46.38), (24.80, 22.80), (62.61, 22.80), (62.61, 23.38)],
    },
    {
        "name": "e22-dio1-fanout",
        "net": "E22_DIO1",
        "layer": "F.Cu",
        "width": 0.20,
        "points": [(30.35, 41.30), (26.00, 41.30)],
    },
    {
        "name": "e22-dio1-backbone",
        "net": "E22_DIO1",
        "layer": "In2.Cu",
        "width": 0.20,
        "points": [(26.00, 41.30), (26.00, 25.50), (62.61, 25.50), (62.61, 25.92)],
    },
    {
        "name": "e22-busy-fanout",
        "net": "E22_BUSY",
        "layer": "F.Cu",
        "width": 0.20,
        "points": [(30.35, 43.84), (27.20, 43.84)],
    },
    {
        "name": "e22-busy-backbone",
        "net": "E22_BUSY",
        "layer": "In2.Cu",
        "width": 0.20,
        "points": [(27.20, 43.84), (27.20, 28.00), (62.61, 28.00), (62.61, 28.46)],
    },
    {
        "name": "e22-nss-fanout",
        "net": "E22_NSS",
        "layer": "F.Cu",
        "width": 0.20,
        "points": [(30.35, 56.54), (28.40, 56.54)],
    },
    {
        "name": "e22-nss-backbone",
        "net": "E22_NSS",
        "layer": "In2.Cu",
        "width": 0.20,
        "points": [(28.40, 56.54), (28.40, 30.60), (62.61, 30.60), (62.61, 31.00)],
    },
    {
        "name": "e22-rxen-direct",
        "net": "E22_RXEN",
        "layer": "F.Cu",
        "width": 0.15,
        "points": [(53.65, 51.46), (54.20, 51.46), (54.20, 50.40)],
    },
    {
        "name": "e22-rxen-bottom-escape-p",
        "net": "E22_RXEN",
        "layer": "B.Cu",
        "width": 0.15,
        "points": [(54.20, 50.40), (54.20, 39.20), (62.61, 39.20), (62.61, 38.62)],
    },
    {
        "name": "e22-sck-fanout",
        "net": "SPI_SCK",
        "layer": "F.Cu",
        "width": 0.20,
        "points": [(30.35, 54.00), (22.80, 54.00)],
    },
    {
        "name": "e22-sck-backbone",
        "net": "SPI_SCK",
        "layer": "B.Cu",
        "width": 0.20,
        "points": [(22.80, 54.00), (22.80, 24.60), (88.00, 24.60), (88.00, 25.92)],
    },
    {
        "name": "e22-sck-xiao-entry",
        "net": "SPI_SCK",
        "layer": "F.Cu",
        "width": 0.20,
        "points": [(88.00, 25.92), (80.39, 25.92)],
    },
    {
        "name": "e22-miso-fanout",
        "net": "SPI_MISO",
        "layer": "F.Cu",
        "width": 0.20,
        "points": [(30.35, 48.92), (23.80, 48.92)],
    },
    {
        "name": "e22-miso-backbone",
        "net": "SPI_MISO",
        "layer": "B.Cu",
        "width": 0.20,
        "points": [(23.80, 48.92), (23.80, 27.00), (87.00, 27.00), (87.00, 28.46)],
    },
    {
        "name": "e22-miso-xiao-entry",
        "net": "SPI_MISO",
        "layer": "F.Cu",
        "width": 0.20,
        "points": [(87.00, 28.46), (80.39, 28.46)],
    },
    {
        "name": "e22-mosi-fanout",
        "net": "SPI_MOSI",
        "layer": "F.Cu",
        "width": 0.20,
        "points": [(30.35, 51.46), (29.60, 51.46)],
    },
    {
        "name": "e22-mosi-backbone",
        "net": "SPI_MOSI",
        "layer": "B.Cu",
        "width": 0.20,
        "points": [(29.60, 51.46), (29.60, 32.20), (86.00, 32.20), (86.00, 31.00)],
    },
    {
        "name": "e22-mosi-xiao-entry",
        "net": "SPI_MOSI",
        "layer": "F.Cu",
        "width": 0.20,
        "points": [(86.00, 31.00), (80.39, 31.00)],
    },
]

VIAS = [
    {"name": "i2c-pullup-sda-via", "net": "I2C_SDA", "at": (86.62, 32.00)},
    {"name": "i2c-pullup-scl-via", "net": "I2C_SCL", "at": (87.60, 34.60)},
    {"name": "bq-sda-via", "net": "I2C_SDA", "at": (67.20, 78.80)},
    {"name": "bq-scl-via", "net": "I2C_SCL", "at": (64.80, 80.60)},
    {"name": "d1-3v3-via", "net": "3V3", "at": (33.50, 91.50)},
    {"name": "r204-3v3-local-via-b", "net": "3V3", "at": (69.68, 72.80)},
    {"name": "r204-3v3-service-rejoin-via-c", "net": "3V3", "at": (90.40, 36.70)},
    {"name": "bq-ts-divider-via", "net": "BQ_TS", "at": (34.38, 87.80)},
    {"name": "bq-ts-u1-via", "net": "BQ_TS", "at": (68.00, 76.60)},
    {"name": "j6-sda-service-via", "net": "I2C_SDA", "at": (95.63, 24.45)},
    {"name": "j6-scl-service-via", "net": "I2C_SCL", "at": (96.88, 24.45)},
    {"name": "j3-xiao-bat-iso-u2-via", "net": "XIAO_BAT_ISO", "at": (85.60, 50.30)},
    {"name": "j3-xiao-bat-iso-pad-via", "net": "XIAO_BAT_ISO", "at": (94.38, 87.80)},
    {"name": "j4-ntc-sense-r201-via", "net": "NTC_SENSE", "at": (36.03, 89.00)},
    {"name": "j4-ntc-sense-pad-via", "net": "NTC_SENSE", "at": (83.88, 86.65)},
    {"name": "bq-sys-c205-bus-via", "net": "BQ_SYS", "at": (40.50, 83.40)},
    {"name": "bq-sys-c205-pad-via", "net": "BQ_SYS", "at": (50.00, 77.80)},
    {"name": "bq-sys-u1-entry-via-b", "net": "BQ_SYS", "at": (65.80, 71.80)},
    {"name": "bq-sys-l2-spine-via-b", "net": "BQ_SYS", "at": (70.50, 55.00)},
    {"name": "bq-sys-u3-vin-via-b", "net": "BQ_SYS", "at": (61.20, 52.90)},
    {"name": "solar-prot-gate-u4-via-b", "net": "SOLAR_PROT_GATE", "at": (76.60, 49.03)},
    {"name": "solar-prot-gate-q1-via-b", "net": "SOLAR_PROT_GATE", "at": (74.00, 55.37)},
    {"name": "q1-solar-prot-common-left-via", "net": "SOLAR_PROT_COMMON", "at": (72.50, 54.10)},
    {"name": "q1-solar-prot-common-right-via", "net": "SOLAR_PROT_COMMON", "at": (82.00, 56.64)},
    {"name": "q2-solar-selector-common-left-via-b", "net": "BQ_SOLAR_SELECTOR_COMMON", "at": (72.50, 62.10)},
    {"name": "q2-solar-selector-common-right-via-b", "net": "BQ_SOLAR_SELECTOR_COMMON", "at": (82.00, 64.64)},
    {"name": "q2-acdrv1-u1-via-b", "net": "BQ_ACDRV1", "at": (63.20, 78.40)},
    {"name": "q2-acdrv1-gate-via-b", "net": "BQ_ACDRV1", "at": (73.50, 64.80)},
    {"name": "q3-usb-selector-common-left-via-b", "net": "BQ_USB_SELECTOR_COMMON", "at": (72.50, 70.10)},
    {"name": "q3-usb-selector-common-right-via-b", "net": "BQ_USB_SELECTOR_COMMON", "at": (82.00, 72.64)},
    {"name": "q3-acdrv2-u1-via-b", "net": "BQ_ACDRV2", "at": (61.60, 77.60)},
    {"name": "q3-acdrv2-gate-via-b", "net": "BQ_ACDRV2", "at": (74.20, 72.10)},
    {"name": "solar-protected-u4-sense-via-b", "net": "SOLAR_PROTECTED", "at": (76.10, 49.68)},
    {"name": "solar-protected-q1-left-drain-via-b", "net": "SOLAR_PROTECTED", "at": (75.38, 56.64)},
    {"name": "solar-protected-q1-right-drain-via-b", "net": "SOLAR_PROTECTED", "at": (80.63, 61.70)},
    {"name": "bq-pmid-c213-bus-via", "net": "BQ_PMID", "at": (32.60, 75.00)},
    {"name": "bq-pmid-c213-pad-via", "net": "BQ_PMID", "at": (27.60, 85.80)},
    {"name": "bq-pmid-u1-via-f", "net": "BQ_PMID", "at": (64.00, 72.45), "size": 0.50, "drill": 0.25},
    {"name": "bq-pmid-capbus-via-f", "net": "BQ_PMID", "at": (45.50, 71.50), "size": 0.50, "drill": 0.25},
    {"name": "bq-vbus-c212-bus-via", "net": "BQ_VBUS", "at": (21.40, 75.00)},
    {"name": "bq-vbus-c212-pad-via", "net": "BQ_VBUS", "at": (22.40, 85.80)},
    {"name": "bq-vbus-u1-to-capbank-via-x", "net": "BQ_VBUS", "at": (62.05, 74.10), "size": 0.50, "drill": 0.25},
    {"name": "bq-vbus-q2-via", "net": "BQ_VBUS", "at": (83.50, 65.91)},
    {"name": "bq-vbus-q2-left-drain-via-b", "net": "BQ_VBUS", "at": (75.38, 64.64)},
    {"name": "bq-vbus-q3-via", "net": "BQ_VBUS", "at": (83.50, 73.91)},
    {"name": "bq-vbus-q3-left-drain-via-b", "net": "BQ_VBUS", "at": (75.38, 72.64)},
    {"name": "bat-raw-u2-branch-via-b", "net": "BAT_RAW", "at": (82.00, 47.60)},
    {"name": "bat-raw-branch-layer-via-b", "net": "BAT_RAW", "at": (86.00, 82.00)},
    {"name": "bat-raw-cap-bus-via-b", "net": "BAT_RAW", "at": (50.53, 81.00)},
    {"name": "bat-raw-u1-entry-via-b", "net": "BAT_RAW", "at": (68.00, 74.00)},
    {"name": "solar-fused-fuse-via", "net": "SOLAR_FUSED", "at": (89.60, 54.00)},
    {"name": "solar-fused-q1-via", "net": "SOLAR_FUSED", "at": (80.63, 52.20)},
    {"name": "solar-fused-u4-via-b", "net": "SOLAR_FUSED", "at": (71.80, 49.03)},
    {"name": "solar-fused-r100-local-via", "net": "SOLAR_FUSED", "at": (66.30, 43.80)},
    {"name": "solar-fused-r103-pullup-via", "net": "SOLAR_FUSED", "at": (77.58, 47.80)},
    {"name": "bq-stat-r207-via", "net": "BQ_STAT", "at": (42.60, 93.00)},
    {"name": "bq-stat-u1-via", "net": "BQ_STAT", "at": (62.40, 73.40)},
    {"name": "bq-regn-u1-pad5-via-a", "net": "BQ_REGN", "at": (60.80, 76.00)},
    {"name": "bq-regn-c215-via-a", "net": "BQ_REGN", "at": (39.85, 85.00)},
    {"name": "batp-kelvin-u1-via-e", "net": "BATP_KELVIN", "at": (67.75, 75.90), "size": 0.50, "drill": 0.25},
    {"name": "batp-kelvin-layer-hop-via-e", "net": "BATP_KELVIN", "at": (49.00, 80.20), "size": 0.50, "drill": 0.25},
    {"name": "batp-kelvin-r202-via-e", "net": "BATP_KELVIN", "at": (42.45, 90.50), "size": 0.50, "drill": 0.25},
    {"name": "boost-fb-u3-via-b", "net": "BOOST_FB", "at": (56.60, 55.55)},
    {"name": "boost-fb-r400-via-b", "net": "BOOST_FB", "at": (42.13, 30.00)},
    {"name": "boost-en-u3-via-b", "net": "BOOST_EN", "at": (60.65, 58.50)},
    {"name": "boost-en-xiao-via-b", "net": "BOOST_EN", "at": (84.00, 23.38)},
    {"name": "boost-en-r405-via-b", "net": "BOOST_EN", "at": (21.18, 48.20)},
    {"name": "e22-nrst-via", "net": "E22_NRST", "at": (24.80, 46.38)},
    {"name": "e22-dio1-via", "net": "E22_DIO1", "at": (26.00, 41.30)},
    {"name": "e22-busy-via", "net": "E22_BUSY", "at": (27.20, 43.84)},
    {"name": "e22-nss-via", "net": "E22_NSS", "at": (28.40, 56.54)},
    {"name": "e22-rxen-bottom-via-p", "net": "E22_RXEN", "at": (54.20, 50.40), "size": 0.50, "drill": 0.25},
    {"name": "e22-sck-e22-via", "net": "SPI_SCK", "at": (22.80, 54.00)},
    {"name": "e22-sck-xiao-via", "net": "SPI_SCK", "at": (88.00, 25.92)},
    {"name": "e22-miso-e22-via", "net": "SPI_MISO", "at": (23.80, 48.92)},
    {"name": "e22-miso-xiao-via", "net": "SPI_MISO", "at": (87.00, 28.46)},
    {"name": "e22-mosi-e22-via", "net": "SPI_MOSI", "at": (29.60, 51.46)},
    {"name": "e22-mosi-xiao-via", "net": "SPI_MOSI", "at": (86.00, 31.00)},
]

def stable_uuid(*parts: str) -> str:
    return str(uuid.uuid5(NAMESPACE, "::".join(parts)))


GROUND_ZONES = [
    ("F.Cu", "TOP_GND_FILL", stable_uuid("zone", "top-ground-fill")),
    ("In1.Cu", "L2_GND_REFERENCE", stable_uuid("zone", "l2-ground-reference")),
]
RETIRED_GENERATED_UUIDS = {
    "0b7b61b1-618b-5f4e-b2f7-e2ab289b7a29",
    "20391620-8499-5247-99ac-f97ff61a93ca",
    stable_uuid("zone", "bottom-ground-fill"),
    stable_uuid("segment", "e22-rxen-direct", "1"),
    stable_uuid("segment", "e22-rxen-direct", "2"),
    stable_uuid("segment", "e22-rxen-direct", "3"),
    stable_uuid("segment", "e22-rxen-backbone", "1"),
    stable_uuid("segment", "e22-rxen-backbone", "2"),
    stable_uuid("via", "e22-rxen-via"),
    stable_uuid("segment", "j6-3v3-fanout", "0"),
    stable_uuid("segment", "j6-3v3-fanout", "1"),
    stable_uuid("segment", "j6-3v3-backbone", "0"),
    stable_uuid("segment", "j6-3v3-backbone", "1"),
    stable_uuid("segment", "j6-3v3-backbone", "2"),
    stable_uuid("via", "d1-3v3-service-via"),
    stable_uuid("segment", "d1-3v3-internal-route", "2"),
    stable_uuid("segment", "j6-gnd-fanout", "0"),
    stable_uuid("segment", "j6-gnd-backbone", "0"),
    stable_uuid("segment", "j6-gnd-backbone", "1"),
    stable_uuid("segment", "j6-gnd-backbone", "2"),
    stable_uuid("segment", "j6-sda-fanout", "0"),
    stable_uuid("segment", "j6-sda-fanout", "1"),
    stable_uuid("segment", "j6-sda-backbone", "0"),
    stable_uuid("segment", "j6-sda-backbone", "1"),
    stable_uuid("segment", "j6-sda-backbone", "2"),
    stable_uuid("segment", "j6-sda-backbone", "3"),
    stable_uuid("segment", "j6-scl-fanout", "0"),
    stable_uuid("segment", "j6-scl-fanout", "1"),
    stable_uuid("segment", "j6-scl-backbone", "0"),
    stable_uuid("segment", "j6-scl-backbone", "1"),
    stable_uuid("segment", "j6-scl-backbone", "2"),
    stable_uuid("segment", "j6-scl-backbone", "3"),
    stable_uuid("segment", "i2c-scl-xiao-entry", "2"),
    stable_uuid("segment", "bq-prog-local-route", "0"),
    stable_uuid("segment", "bq-prog-local-route", "1"),
    stable_uuid("segment", "bq-prog-local-route", "2"),
    stable_uuid("segment", "bq-prog-local-route", "3"),
    stable_uuid("segment", "bq-int-local-route", "0"),
    stable_uuid("segment", "bq-int-local-route", "1"),
    stable_uuid("segment", "bq-int-local-route", "2"),
    stable_uuid("segment", "bq-int-local-route", "3"),
    stable_uuid("segment", "5v-radio-u3-fanout-b", "0"),
    stable_uuid("segment", "5v-radio-u3-fanout-b", "1"),
    stable_uuid("segment", "5v-radio-u3-to-e22-b", "0"),
    stable_uuid("segment", "5v-radio-u3-to-e22-b", "1"),
    stable_uuid("segment", "5v-radio-u3-to-e22-b", "2"),
    stable_uuid("via", "5v-radio-u3-via-b"),
    stable_uuid("segment", "bq-regn-u1-pins-local-bridge-c", "0"),
    stable_uuid("segment", "bq-regn-u1-pins-local-bridge-c", "1"),
    stable_uuid("segment", "bq-regn-u1-pins-local-bridge-c", "2"),
    stable_uuid("segment", "bq-regn-u1-pin5-fanout-c", "0"),
    stable_uuid("segment", "bq-regn-u1-pin17-fanout-c", "0"),
    stable_uuid("via", "bq-regn-u1-pin5-via-c"),
    stable_uuid("via", "bq-regn-u1-pin17-via-c"),
    stable_uuid("segment", "boost-vcc-c405-local-d", "0"),
    stable_uuid("segment", "boost-vcc-c405-local-d", "1"),
    stable_uuid("segment", "boost-vcc-c405-local-d", "2"),
    stable_uuid("segment", "boost-vcc-u3-c405-local-a", "0"),
    stable_uuid("segment", "boost-vcc-c405-local-g", "0"),
    stable_uuid("segment", "boost-vcc-c405-local-g", "1"),
    stable_uuid("segment", "bq-btst2-u1-to-c217-d", "0"),
    stable_uuid("segment", "bq-btst2-u1-to-c217-d", "1"),
    stable_uuid("segment", "bq-btst2-u1-to-c217-d", "2"),
    stable_uuid("segment", "5v-radio-u3-lower-fanout-c", "0"),
    stable_uuid("segment", "5v-radio-lower-corridor-c", "0"),
    stable_uuid("segment", "5v-radio-lower-corridor-c", "1"),
    stable_uuid("segment", "5v-radio-e22-entry-c", "0"),
    stable_uuid("segment", "5v-radio-e22-entry-c", "1"),
    stable_uuid("via", "5v-radio-u3-lower-via-c"),
    stable_uuid("via", "5v-radio-e22-entry-via-c"),
    stable_uuid("segment", "5v-radio-u3-to-e22-rotated-o", "2"),
    stable_uuid("segment", "boost-vcc-c405-local-e", "0"),
    stable_uuid("segment", "boost-vcc-c405-local-e", "1"),
    stable_uuid("segment", "boost-vcc-u3-c405-local-b", "0"),
    stable_uuid("segment", "boost-vcc-u3-c405-local-b", "1"),
    stable_uuid("segment", "boost-ilim-u3-fanout", "1"),
    stable_uuid("segment", "bq-sys-boost-input-to-u3-c", "0"),
    stable_uuid("segment", "bq-sys-boost-input-to-u3-c", "1"),
    stable_uuid("segment", "bq-sys-boost-input-to-u3-c", "2"),
    stable_uuid("segment", "bq-sys-boost-input-to-u3-c", "3"),
    stable_uuid("via", "boost-input-c401-top-bridge-via"),
    stable_uuid("via", "boost-input-c404-top-bridge-via"),
    stable_uuid("segment", "boost-input-c400-c401-local-bus", "1"),
    stable_uuid("segment", "boost-input-c400-c401-local-bus", "2"),
    stable_uuid("segment", "boost-input-c404-top-edge-bridge", "2"),
    stable_uuid("segment", "e22-vcc-c503-local-c", "0"),
    stable_uuid("segment", "e22-vcc-c503-local-c", "1"),
    stable_uuid("segment", "bq-pmid-cap-to-u1-left-fanout-d", "0"),
    stable_uuid("segment", "bq-pmid-cap-to-u1-internal-d", "0"),
    stable_uuid("segment", "bq-pmid-u1-entry-d", "0"),
    stable_uuid("segment", "bq-pmid-u1-entry-d", "1"),
    stable_uuid("via", "bq-pmid-cap-to-u1-via-d"),
    stable_uuid("via", "bq-pmid-u1-entry-via-d"),
    stable_uuid("segment", "bq-sw1-u1-to-l1-top-c", "0"),
    stable_uuid("segment", "bq-sw1-u1-to-l1-top-c", "1"),
    stable_uuid("segment", "bq-sw2-l1-c217-local-b", "0"),
    stable_uuid("segment", "bq-sw2-l1-c217-local-b", "1"),
    stable_uuid("segment", "bq-sw2-l1-c217-local-b", "2"),
    stable_uuid("segment", "bq-sw1-u1-to-l1-placement-d", "0"),
    stable_uuid("segment", "bq-sw1-u1-to-l1-placement-d", "1"),
    stable_uuid("segment", "bq-sw2-u1-to-l1-placement-d", "0"),
    stable_uuid("segment", "bq-sw2-u1-to-l1-placement-d", "1"),
    stable_uuid("segment", "bq-sw2-u1-to-l1-right-wrap-e", "0"),
    stable_uuid("segment", "bq-sw2-u1-to-l1-right-wrap-e", "1"),
    stable_uuid("segment", "bq-sw2-u1-to-l1-right-wrap-e", "2"),
    stable_uuid("segment", "bq-sw2-u1-to-l1-right-wrap-e", "3"),
    stable_uuid("segment", "bq-sw2-u1-to-l1-right-wrap-e", "4"),
    stable_uuid("segment", "bq-sw2-u1-to-l1-right-wrap-e", "5"),
    stable_uuid("segment", "bq-sw2-u1-to-l1-sys-shift-f", "0"),
    stable_uuid("segment", "bq-sw2-u1-to-l1-sys-shift-f", "1"),
    stable_uuid("segment", "bq-sw2-u1-to-l1-sys-shift-f", "2"),
    stable_uuid("segment", "bq-sw2-u1-to-l1-sys-shift-f", "3"),
    stable_uuid("segment", "bq-sw2-u1-to-l1-l", "0"),
    stable_uuid("segment", "bq-sw2-u1-to-l1-l", "1"),
    stable_uuid("segment", "bq-sw2-u1-to-l1-l", "2"),
    stable_uuid("segment", "bq-sw2-u1-to-l1-l", "3"),
    stable_uuid("segment", "bq-sw2-u1-via-escape-m", "0"),
    stable_uuid("segment", "bq-sw2-inner-route-m", "0"),
    stable_uuid("segment", "bq-sw2-inner-route-m", "1"),
    stable_uuid("segment", "bq-sw2-inner-route-m", "2"),
    stable_uuid("segment", "bq-sw2-inner-route-m", "3"),
    stable_uuid("via", "bq-sw2-u1-via-m"),
    stable_uuid("via", "bq-sw2-l1-via-m"),
    stable_uuid("segment", "bq-vbus-u1-to-q3-bottom-n", "0"),
    stable_uuid("segment", "bq-vbus-u1-to-q3-bottom-n", "1"),
    stable_uuid("segment", "bq-vbus-u1-via-fanout-n", "0"),
    stable_uuid("via", "bq-vbus-u1-via-n"),
    stable_uuid("segment", "bat-raw-r202-to-cap-bus-branch", "1"),
    stable_uuid("segment", "bat-raw-r202-to-cap-bus-branch", "2"),
    stable_uuid("segment", "bat-raw-r202-to-cap-bus-branch", "3"),
    stable_uuid("segment", "batp-kelvin-r202-to-u1-c", "0"),
    stable_uuid("segment", "bq-regn-u1-top-wrap-d", "0"),
    stable_uuid("segment", "bq-regn-u1-top-wrap-d", "1"),
    stable_uuid("segment", "bq-regn-u1-top-wrap-d", "2"),
    stable_uuid("segment", "bq-regn-u1-top-wrap-d", "3"),
    stable_uuid("segment", "bq-regn-u1-top-wrap-d", "4"),
    stable_uuid("segment", "boost-fb-divider-local", "0"),
    stable_uuid("segment", "boost-fb-divider-local", "1"),
    stable_uuid("segment", "boost-fb-divider-local", "2"),
    stable_uuid("segment", "boost-fb-divider-local", "3"),
    stable_uuid("segment", "boost-comp-u3-r404-local", "0"),
    stable_uuid("segment", "boost-comp-u3-r404-local", "1"),
    stable_uuid("segment", "boost-comp-u3-r404-local", "2"),
    stable_uuid("segment", "boost-comp-rc-r404-c408-local", "0"),
    stable_uuid("segment", "boost-comp-rc-bottom-route", "0"),
    stable_uuid("segment", "boost-comp-rc-bottom-route", "1"),
    stable_uuid("segment", "boost-comp-rc-bottom-route", "2"),
    stable_uuid("segment", "boost-comp-rc-c408-fanout", "0"),
    stable_uuid("via", "boost-comp-rc-r404-via"),
    stable_uuid("via", "boost-comp-rc-c408-via"),
    stable_uuid("segment", "j3-xiao-bat-iso-service-route", "3"),
    stable_uuid("segment", "batp-kelvin-service-route", "0"),
    stable_uuid("segment", "batp-kelvin-service-route", "1"),
    stable_uuid("segment", "batp-kelvin-service-route", "2"),
    stable_uuid("segment", "batp-kelvin-service-route", "3"),
    stable_uuid("segment", "batp-kelvin-r202-fanout", "0"),
    stable_uuid("segment", "batp-kelvin-bottom-route", "0"),
    stable_uuid("segment", "batp-kelvin-bottom-route", "1"),
    stable_uuid("segment", "batp-kelvin-u1-fanout", "0"),
    stable_uuid("segment", "batp-kelvin-r202-local", "0"),
    stable_uuid("segment", "batp-kelvin-r202-local", "1"),
    stable_uuid("segment", "bat-raw-r202-local", "0"),
    stable_uuid("segment", "bat-raw-r202-local", "1"),
    stable_uuid("segment", "bat-raw-u2-entry-b", "1"),
    stable_uuid("segment", "bat-raw-u2-entry-b", "2"),
    stable_uuid("segment", "bat-raw-branch-to-cap-bus-b", "1"),
    stable_uuid("segment", "bat-raw-branch-to-cap-bus-b", "2"),
    stable_uuid("segment", "uv-divider-local", "1"),
    stable_uuid("segment", "uv-divider-local", "2"),
    stable_uuid("segment", "uv-divider-local", "3"),
    stable_uuid("segment", "uv-divider-local", "4"),
    stable_uuid("segment", "uv-divider-local", "5"),
    stable_uuid("segment", "ov-divider-local", "1"),
    stable_uuid("segment", "ov-divider-local", "2"),
    stable_uuid("segment", "ov-divider-local", "3"),
    stable_uuid("segment", "ov-node-u4-local", "2"),
    stable_uuid("segment", "solar-fused-divider-bottom-jog", "0"),
    stable_uuid("segment", "solar-fused-divider-bottom-jog", "1"),
    stable_uuid("segment", "solar-fused-divider-bottom-jog", "2"),
    stable_uuid("segment", "solar-fused-divider-r103-fanout", "0"),
    stable_uuid("segment", "solar-fused-divider-r100-fanout", "1"),
    stable_uuid("segment", "solar-fused-divider-r100-fanout", "2"),
    stable_uuid("segment", "solar-fused-divider-r100-fanout", "3"),
    stable_uuid("via", "solar-fused-divider-r100-via"),
    stable_uuid("via", "solar-fused-divider-r103-via"),
    stable_uuid("segment", "ov-divider-local", "4"),
    stable_uuid("segment", "ov-divider-local", "5"),
    stable_uuid("segment", "ltc-shdn-local", "0"),
    stable_uuid("segment", "r204-3v3-fanout", "0"),
    stable_uuid("segment", "r204-3v3-backbone", "0"),
    stable_uuid("segment", "r204-3v3-backbone", "1"),
    stable_uuid("segment", "r204-3v3-backbone", "2"),
    stable_uuid("segment", "r204-3v3-service-edge-route", "0"),
    stable_uuid("segment", "r204-3v3-service-edge-route", "1"),
    stable_uuid("segment", "r204-3v3-service-edge-route", "2"),
    stable_uuid("segment", "r204-3v3-service-edge-route", "3"),
    stable_uuid("segment", "r204-3v3-internal-service-b", "0"),
    stable_uuid("segment", "r204-3v3-internal-service-b", "1"),
    stable_uuid("segment", "r204-3v3-right-edge-service-b", "0"),
    stable_uuid("segment", "r204-3v3-right-edge-service-b", "1"),
    stable_uuid("segment", "r204-3v3-right-edge-service-b", "2"),
    stable_uuid("segment", "q1-solar-prot-common-local", "0"),
    stable_uuid("segment", "q1-solar-prot-common-local", "1"),
    stable_uuid("segment", "q1-solar-prot-common-local", "2"),
    stable_uuid("segment", "solar-prot-gate-u4-fanout", "0"),
    stable_uuid("segment", "solar-prot-gate-backbone", "0"),
    stable_uuid("segment", "solar-prot-gate-q1-entry", "0"),
    stable_uuid("segment", "solar-prot-gate-u4-to-q1", "0"),
    stable_uuid("segment", "solar-prot-gate-u4-to-q1", "1"),
    stable_uuid("segment", "solar-prot-gate-u4-to-q1", "2"),
    stable_uuid("segment", "solar-prot-gate-u4-to-q1", "3"),
    stable_uuid("segment", "solar-fused-fuse-to-q1", "0"),
    stable_uuid("segment", "solar-fused-fuse-to-q1", "1"),
    stable_uuid("segment", "solar-fused-fuse-to-q1", "2"),
    stable_uuid("segment", "solar-fused-backbone", "2"),
    stable_uuid("segment", "solar-fused-divider-to-u4-backbone", "0"),
    stable_uuid("segment", "solar-fused-divider-to-u4-backbone", "1"),
    stable_uuid("segment", "solar-protected-u4-fanout", "0"),
    stable_uuid("segment", "solar-protected-u4-sense-backbone", "0"),
    stable_uuid("segment", "solar-protected-u4-sense-backbone", "1"),
    stable_uuid("segment", "solar-protected-q1-sense-entry", "0"),
    stable_uuid("segment", "solar-protected-q1-sense-entry", "1"),
    stable_uuid("segment", "boost-ss-u3-to-c407", "0"),
    stable_uuid("segment", "boost-ss-u3-to-c407", "1"),
    stable_uuid("segment", "boost-ss-u3-to-c407", "2"),
    stable_uuid("segment", "boost-bq-sys-u3-to-l2", "0"),
    stable_uuid("segment", "boost-bq-sys-u3-to-l2", "1"),
    stable_uuid("segment", "boost-bq-sys-u3-to-l2", "2"),
    stable_uuid("segment", "boost-bq-sys-u3-to-l2", "3"),
    stable_uuid("segment", "usb-vbus-q3-fanout", "0"),
    stable_uuid("segment", "usb-vbus-xiao-backbone", "0"),
    stable_uuid("segment", "usb-vbus-xiao-backbone", "1"),
    stable_uuid("segment", "usb-vbus-xiao-backbone", "2"),
    stable_uuid("segment", "usb-vbus-raw-q3-right-stub-b", "0"),
    stable_uuid("segment", "usb-vbus-raw-xiao-to-q3-b", "0"),
    stable_uuid("segment", "usb-vbus-raw-xiao-to-q3-b", "1"),
    stable_uuid("segment", "usb-vbus-raw-xiao-to-q3-b", "2"),
    stable_uuid("segment", "usb-vbus-raw-xiao-to-q3-b", "3"),
    stable_uuid("segment", "usb-vbus-raw-q3-to-u1-b", "0"),
    stable_uuid("segment", "usb-vbus-raw-q3-to-u1-b", "1"),
    stable_uuid("segment", "usb-vbus-raw-q3-to-u1-b", "2"),
    stable_uuid("segment", "usb-vbus-raw-q3-to-u1-b", "3"),
    stable_uuid("segment", "usb-vbus-raw-u1-entry-b", "0"),
    stable_uuid("segment", "bq-pmid-cap-bank-bus", "2"),
    stable_uuid("segment", "bq-pmid-c213-stub", "0"),
    stable_uuid("via", "usb-vbus-q3-via"),
    stable_uuid("via", "usb-vbus-raw-q3-via-b"),
    stable_uuid("via", "usb-vbus-raw-u1-via-b"),
    stable_uuid("via", "solar-protected-u4-via"),
    stable_uuid("via", "solar-protected-q1-via"),
    stable_uuid("segment", "q2-solar-selector-common-local", "0"),
    stable_uuid("segment", "q2-solar-selector-common-local", "1"),
    stable_uuid("segment", "q2-solar-selector-common-local", "2"),
    stable_uuid("segment", "q3-usb-selector-common-local", "0"),
    stable_uuid("segment", "q3-usb-selector-common-local", "1"),
    stable_uuid("segment", "q3-usb-selector-common-local", "2"),
    stable_uuid("segment", "bq-vbus-q2-left-drain-loop", "0"),
    stable_uuid("segment", "bq-vbus-q2-left-drain-loop", "1"),
    stable_uuid("segment", "bq-vbus-q2-left-drain-loop", "2"),
    stable_uuid("segment", "bq-vbus-q2-left-drain-loop", "3"),
    stable_uuid("segment", "bq-vbus-q3-left-drain-loop", "0"),
    stable_uuid("segment", "bq-vbus-q3-left-drain-loop", "1"),
    stable_uuid("segment", "bq-vbus-q3-left-drain-loop", "2"),
    stable_uuid("segment", "bq-vbus-q3-left-drain-loop", "3"),
    stable_uuid("segment", "q2-acdrv1-backbone", "0"),
    stable_uuid("segment", "q2-acdrv1-backbone", "1"),
    stable_uuid("segment", "q2-acdrv1-backbone", "2"),
    stable_uuid("segment", "q2-acdrv1-u1-fanout", "0"),
    stable_uuid("segment", "q2-acdrv1-u1-fanout", "1"),
    stable_uuid("segment", "q2-acdrv1-u1-fanout", "2"),
    stable_uuid("segment", "q3-acdrv2-backbone", "0"),
    stable_uuid("segment", "q3-acdrv2-backbone", "1"),
    stable_uuid("segment", "q3-acdrv2-backbone", "2"),
    stable_uuid("segment", "q3-acdrv2-u1-fanout", "0"),
    stable_uuid("segment", "q3-acdrv2-u1-fanout", "1"),
    stable_uuid("segment", "q3-acdrv2-u1-fanout", "2"),
    stable_uuid("segment", "q3-acdrv2-u1-top-route", "0"),
    stable_uuid("segment", "q3-acdrv2-u1-top-route", "1"),
    stable_uuid("segment", "q3-acdrv2-u1-top-route", "2"),
    stable_uuid("segment", "q3-acdrv2-u1-top-route", "3"),
    stable_uuid("segment", "q3-acdrv2-u1-fanout-b", "2"),
    stable_uuid("segment", "solar-raw-xt30-to-fuse", "2"),
    stable_uuid("via", "q2-acdrv1-u1-via"),
    stable_uuid("via", "q2-acdrv1-gate-via"),
    stable_uuid("via", "q3-acdrv2-u1-via"),
    stable_uuid("via", "q3-acdrv2-gate-via"),
    stable_uuid("via", "solar-prot-gate-u4-via"),
    stable_uuid("via", "solar-prot-gate-q1-via"),
    stable_uuid("via", "r204-3v3-via"),
    stable_uuid("via", "r204-3v3-spine-via"),
    stable_uuid("via", "batp-kelvin-r202-via"),
    stable_uuid("via", "batp-kelvin-u1-via"),
    stable_uuid("via", "batp-kelvin-r202-via-b"),
    stable_uuid("via", "batp-kelvin-u1-via-b"),
    stable_uuid("segment", "boost-en-u3-via-fanout", "0"),
    stable_uuid("segment", "boost-en-u3-via-fanout", "1"),
    stable_uuid("segment", "boost-en-u3-via-fanout", "2"),
    stable_uuid("segment", "boost-en-u3-fanout-b", "1"),
    stable_uuid("segment", "boost-en-xiao-backbone", "0"),
    stable_uuid("segment", "boost-en-xiao-backbone", "1"),
    stable_uuid("segment", "boost-en-xiao-backbone", "2"),
    stable_uuid("segment", "boost-en-xiao-backbone", "3"),
    stable_uuid("segment", "boost-en-r405-link", "0"),
    stable_uuid("segment", "boost-en-r405-link", "1"),
    stable_uuid("segment", "boost-en-r405-link", "2"),
    stable_uuid("segment", "boost-en-r405-ground", "0"),
    stable_uuid("segment", "boost-en-local-pulldown", "0"),
    stable_uuid("segment", "boost-en-pulldown-ground", "0"),
    stable_uuid("segment", "u3-boost-en-pulldown-local", "0"),
    stable_uuid("segment", "bq-ts-u1-to-r200-local", "0"),
    stable_uuid("segment", "u1-regn-ilim-local", "0"),
    stable_uuid("segment", "u1-regn-ilim-local", "1"),
    stable_uuid("segment", "u1-regn-ilim-local", "2"),
    stable_uuid("segment", "u1-regn-ilim-local", "3"),
    stable_uuid("segment", "u1-regn-ilim-local", "4"),
    stable_uuid("segment", "u1-regn-ilim-left-fanout", "0"),
    stable_uuid("segment", "u1-regn-ilim-bottom", "0"),
    stable_uuid("segment", "u1-regn-ilim-bottom", "1"),
    stable_uuid("segment", "u1-regn-ilim-bottom", "2"),
    stable_uuid("segment", "u1-regn-ilim-right-fanout", "0"),
    stable_uuid("segment", "u1-regn-ilim-clear-local", "0"),
    stable_uuid("segment", "u1-regn-ilim-clear-local", "1"),
    stable_uuid("segment", "u1-regn-ilim-clear-local", "2"),
    stable_uuid("segment", "u1-regn-ilim-clear-local", "3"),
    stable_uuid("segment", "u1-regn-ilim-clear-local", "4"),
    stable_uuid("segment", "bq-regn-u1-pin-link-trial", "0"),
    stable_uuid("segment", "bq-regn-u1-pin-link-trial", "1"),
    stable_uuid("segment", "bq-regn-u1-pin-link-trial", "2"),
    stable_uuid("segment", "bq-regn-u1-pin-link-trial", "3"),
    stable_uuid("segment", "bq-regn-u1-pin-link-trial", "4"),
    stable_uuid("segment", "protection-gnd-local", "0"),
    stable_uuid("segment", "protection-gnd-local", "1"),
    stable_uuid("segment", "protection-gnd-local", "2"),
    stable_uuid("segment", "protection-gnd-r102-fanout", "0"),
    stable_uuid("segment", "protection-gnd-bottom", "0"),
    stable_uuid("segment", "protection-gnd-r405-fanout", "0"),
    stable_uuid("via", "j6-3v3-via"),
    stable_uuid("via", "j6-gnd-via"),
    stable_uuid("via", "j6-sda-via"),
    stable_uuid("via", "j6-scl-via"),
    stable_uuid("via", "boost-en-xiao-via"),
    stable_uuid("via", "boost-en-r405-gnd-via"),
    stable_uuid("via", "boost-en-pulldown-gnd-via"),
    stable_uuid("via", "u1-regn-ilim-left-via"),
    stable_uuid("via", "u1-regn-ilim-right-via"),
    stable_uuid("via", "protection-gnd-via"),
    stable_uuid("via", "protection-gnd-r102-via"),
    stable_uuid("via", "protection-gnd-r405-via"),
    stable_uuid("via", "e22-sck-via"),
    stable_uuid("via", "e22-miso-via"),
    stable_uuid("via", "e22-mosi-via"),
    stable_uuid("segment", "boost-ilim-internal-run", "0"),
    stable_uuid("segment", "boost-ilim-internal-run", "1"),
    stable_uuid("segment", "boost-ilim-internal-run", "2"),
    stable_uuid("segment", "boost-ilim-r403-fanout", "0"),
    stable_uuid("via", "boost-ilim-u3-via"),
    stable_uuid("via", "boost-ilim-r403-via"),
    stable_uuid("segment", "boost-ss-c407-local", "1"),
    stable_uuid("segment", "boost-vcc-c405-local", "0"),
    stable_uuid("segment", "q1-solar-protected-left-fanout", "0"),
    stable_uuid("segment", "q1-solar-protected-bottom-bridge", "0"),
    stable_uuid("segment", "q1-solar-protected-bottom-bridge", "1"),
    stable_uuid("segment", "q1-solar-protected-bottom-bridge", "2"),
    stable_uuid("segment", "q1-solar-protected-right-entry", "0"),
    stable_uuid("via", "q1-solar-protected-left-via"),
    stable_uuid("via", "q1-solar-protected-right-via"),
    stable_uuid("segment", "bq-btst2-c217-local", "0"),
    stable_uuid("segment", "bq-btst2-c217-local", "1"),
    stable_uuid("segment", "bq-btst2-c217-local", "2"),
    stable_uuid("segment", "bq-btst2-u1-to-c217-b", "0"),
    stable_uuid("segment", "bq-btst2-u1-to-c217-b", "1"),
    stable_uuid("segment", "bq-btst2-u1-to-c217-b", "2"),
    stable_uuid("segment", "bq-btst2-u1-to-c217-b", "3"),
    stable_uuid("segment", "bq-btst2-c217-fanout-b", "0"),
    stable_uuid("segment", "bq-btst2-back-route-b", "0"),
    stable_uuid("segment", "bq-btst2-back-route-b", "1"),
    stable_uuid("segment", "bq-btst2-back-route-b", "2"),
    stable_uuid("segment", "bq-btst2-u1-entry-b", "0"),
    stable_uuid("via", "bq-btst2-c217-via-b"),
    stable_uuid("via", "bq-btst2-u1-via-b"),
    stable_uuid("segment", "bq-btst2-u1-to-c217-top-c", "0"),
    stable_uuid("segment", "bq-btst2-u1-to-c217-top-c", "1"),
    stable_uuid("segment", "bq-btst2-u1-to-c217-top-c", "2"),
    stable_uuid("segment", "bq-btst2-u1-to-c217-top-c", "3"),
    stable_uuid("segment", "bq-btst2-u1-to-c217-pocket-e", "0"),
    stable_uuid("segment", "bq-btst2-u1-to-c217-pocket-e", "1"),
    stable_uuid("segment", "bq-btst2-u1-to-c217-pocket-e", "2"),
    stable_uuid("segment", "bq-btst2-u1-to-c217-pocket-e", "3"),
    stable_uuid("segment", "bq-btst2-c217-local-h", "0"),
    stable_uuid("segment", "bq-prog-u1-fanout-h", "0"),
    stable_uuid("segment", "bq-prog-u1-fanout-h", "1"),
    stable_uuid("segment", "bq-prog-backbone-h", "0"),
    stable_uuid("segment", "bq-prog-backbone-h", "1"),
    stable_uuid("segment", "bq-prog-r203-entry-h", "0"),
    stable_uuid("via", "bq-prog-u1-via-h"),
    stable_uuid("via", "bq-prog-r203-via-h"),
    "1f2c0ff8-3a83-5742-8f68-21b7c4d62c24",  # orphaned BQ_PROG trial stub at rejected R203 placement
    stable_uuid("segment", "bq-sw2-u1-to-l1-right-spine-g", "0"),
    stable_uuid("segment", "bq-sw2-u1-to-l1-right-spine-g", "1"),
    stable_uuid("segment", "bq-sw2-u1-to-l1-right-spine-g", "2"),
    stable_uuid("segment", "boost-vcc-u3-c405-local-h", "0"),
    stable_uuid("segment", "boost-vcc-u3-c405-local-h", "1"),
    stable_uuid("segment", "bq-btst2-u1-fanout-g", "0"),
    stable_uuid("segment", "bq-btst2-u1-fanout-g", "1"),
    stable_uuid("segment", "bq-btst2-backbone-g", "0"),
    stable_uuid("segment", "bq-btst2-backbone-g", "1"),
    stable_uuid("segment", "bq-btst2-backbone-g", "2"),
    stable_uuid("segment", "bq-btst2-c217-entry-g", "0"),
    stable_uuid("segment", "bq-btst2-c217-entry-g", "1"),
    stable_uuid("via", "bq-btst2-u1-via-g"),
    stable_uuid("via", "bq-btst2-c217-via-g"),
    stable_uuid("segment", "bq-btst2-u1-fanout-d", "0"),
    stable_uuid("segment", "bq-btst2-backbone-d", "0"),
    stable_uuid("segment", "bq-btst2-backbone-d", "1"),
    stable_uuid("segment", "bq-btst2-backbone-d", "2"),
    stable_uuid("segment", "bq-btst2-c217-entry-d", "0"),
    stable_uuid("via", "bq-btst2-u1-via-d"),
    stable_uuid("via", "bq-btst2-c217-via-d"),
    stable_uuid("segment", "bq-sw2-c217-local", "0"),
    stable_uuid("segment", "bq-sw2-c217-local", "1"),
    stable_uuid("segment", "bq-sw2-c217-local", "2"),
    stable_uuid("segment", "bq-sw2-u1-to-l1-b", "0"),
    stable_uuid("segment", "bq-sw2-u1-to-l1-b", "1"),
    stable_uuid("segment", "bq-sw2-u1-to-l1-b", "2"),
    stable_uuid("segment", "bq-pmid-u1-to-cap-bus-trial", "1"),
    stable_uuid("segment", "bq-pmid-u1-to-cap-bus-trial", "2"),
    stable_uuid("segment", "bq-pmid-u1-to-cap-bus-trial", "0"),
    stable_uuid("segment", "bq-pmid-u1-to-cap-bus-bottom", "0"),
    stable_uuid("segment", "bq-pmid-u1-to-cap-bus-bottom", "1"),
    stable_uuid("segment", "bq-pmid-u1-to-cap-bus-bottom", "2"),
    stable_uuid("via", "bq-pmid-u1-via"),
    stable_uuid("via", "bq-pmid-cap-bus-via"),
    stable_uuid("segment", "bq-pmid-cap-bus-to-u1-b", "0"),
    stable_uuid("segment", "bq-pmid-cap-bus-to-u1-b", "1"),
    stable_uuid("segment", "bq-pmid-u1-entry-b", "0"),
    stable_uuid("via", "bq-pmid-cap-bus-via-b"),
    stable_uuid("via", "bq-pmid-u1-via-b"),
    stable_uuid("segment", "bq-sw1-c216-local", "2"),
    stable_uuid("segment", "bq-vbus-q3-left-drain-fanout-b", "0"),
    stable_uuid("segment", "solar-protected-q1-left-to-right-b", "2"),
    stable_uuid("segment", "solar-protected-q1-to-u1-b", "0"),
    stable_uuid("segment", "solar-protected-q1-to-u1-b", "1"),
    stable_uuid("segment", "solar-protected-q1-to-u1-b", "2"),
    stable_uuid("via", "solar-protected-u1-entry-via-b"),
    stable_uuid("segment", "solar-protected-u1-entry-c", "0"),
    stable_uuid("segment", "solar-protected-q2-to-u1-c", "0"),
    stable_uuid("segment", "solar-protected-q2-to-u1-c", "1"),
    stable_uuid("via", "solar-protected-u1-entry-via-c"),
    stable_uuid("segment", "solar-protected-u1-fanout-v", "0"),
    stable_uuid("segment", "solar-protected-u1-fanout-v", "1"),
    stable_uuid("segment", "solar-protected-u1-to-q1-v", "0"),
    stable_uuid("segment", "solar-protected-u1-to-q1-v", "1"),
    stable_uuid("segment", "solar-protected-u1-to-q1-v", "2"),
    stable_uuid("via", "solar-protected-u1-via-v"),
    stable_uuid("segment", "boost-comp-u3-fanout-b", "0"),
    stable_uuid("segment", "boost-comp-internal-route-b", "0"),
    stable_uuid("segment", "boost-comp-internal-route-b", "1"),
    stable_uuid("segment", "boost-comp-internal-route-b", "2"),
    stable_uuid("segment", "boost-comp-r404-entry-b", "0"),
    stable_uuid("via", "boost-comp-u3-via-b"),
    stable_uuid("via", "boost-comp-r404-via-b"),
    stable_uuid("segment", "boost-comp-u3-fanout-c", "0"),
    stable_uuid("segment", "boost-comp-u3-to-r404-bottom-c", "0"),
    stable_uuid("segment", "boost-comp-u3-to-r404-bottom-c", "1"),
    stable_uuid("via", "boost-comp-u3-via-c"),
    stable_uuid("via", "boost-comp-r404-via-c"),
    stable_uuid("segment", "boost-comp-r404-perimeter-fanout-a", "0"),
    stable_uuid("segment", "boost-comp-perimeter-route-a", "0"),
    stable_uuid("segment", "boost-comp-perimeter-route-a", "1"),
    stable_uuid("segment", "boost-comp-perimeter-route-a", "2"),
    stable_uuid("segment", "boost-comp-u3-entry-a", "0"),
    stable_uuid("via", "boost-comp-r404-perimeter-via-a"),
    stable_uuid("via", "boost-comp-u3-entry-via-a"),
    stable_uuid("segment", "batp-kelvin-u1-fanout-a", "0"),
    stable_uuid("segment", "batp-kelvin-back-route-a", "0"),
    stable_uuid("segment", "batp-kelvin-back-route-a", "1"),
    stable_uuid("segment", "batp-kelvin-back-route-a", "2"),
    stable_uuid("segment", "batp-kelvin-r202-fanout-a", "0"),
    stable_uuid("via", "batp-kelvin-u1-via-a"),
    stable_uuid("via", "batp-kelvin-r202-via-a"),
    stable_uuid("segment", "bq-btst2-c217-local-a", "0"),
    stable_uuid("segment", "bq-regn-ilim-u1-fanout-a", "0"),
    stable_uuid("segment", "bq-regn-ilim-bridge-a", "0"),
    stable_uuid("via", "bq-regn-ilim-via-a"),
    stable_uuid("segment", "bq-vbus-cap-bank-u1-fanout-a", "0"),
    stable_uuid("segment", "bq-vbus-cap-bank-u1-fanout-a", "1"),
    stable_uuid("segment", "bq-vbus-cap-bank-u1-fanout-a", "2"),
    stable_uuid("segment", "bq-vbus-cap-bank-u1-route-a", "0"),
    stable_uuid("segment", "bq-vbus-cap-bank-u1-route-a", "1"),
    stable_uuid("via", "bq-vbus-u1-via-a"),
    stable_uuid("via", "bq-vbus-cap-bank-via-a"),
    stable_uuid("segment", "boost-vcc-u3-bottom-fanout-a", "0"),
    stable_uuid("segment", "boost-vcc-c405-bottom-entry-a", "0"),
    stable_uuid("via", "boost-vcc-u3-bottom-via-a"),
    stable_uuid("segment", "batp-kelvin-u1-left-escape-b", "0"),
    stable_uuid("segment", "batp-kelvin-u1-left-escape-b", "1"),
    stable_uuid("segment", "batp-kelvin-u1-left-escape-b", "2"),
    stable_uuid("segment", "batp-kelvin-left-route-b", "0"),
    stable_uuid("segment", "batp-kelvin-left-route-b", "1"),
    stable_uuid("segment", "batp-kelvin-left-route-b", "2"),
    stable_uuid("via", "batp-kelvin-u1-left-via-b"),
    stable_uuid("segment", "batp-kelvin-u1-fanout-d", "0"),
    stable_uuid("segment", "batp-kelvin-u1-fanout-d", "1"),
    stable_uuid("segment", "batp-kelvin-bottom-route-d", "0"),
    stable_uuid("segment", "batp-kelvin-bottom-route-d", "1"),
    stable_uuid("segment", "batp-kelvin-bottom-route-d", "2"),
    stable_uuid("segment", "batp-kelvin-bottom-route-d", "3"),
    stable_uuid("segment", "batp-kelvin-bottom-route-d", "4"),
    stable_uuid("segment", "batp-kelvin-bottom-route-d", "5"),
    stable_uuid("segment", "batp-kelvin-r202-fanout-d", "0"),
    stable_uuid("via", "batp-kelvin-u1-via-d"),
    stable_uuid("via", "batp-kelvin-r202-via-d"),
    stable_uuid("segment", "batp-kelvin-u1-r202-local-e", "0"),
    stable_uuid("segment", "batp-kelvin-r202-batraw-local-e", "0"),
    stable_uuid("segment", "batp-kelvin-r202-batraw-local-e", "1"),
    stable_uuid("segment", "bq-pmid-u1-lower-escape-f", "1"),
    stable_uuid("segment", "bq-pmid-u1-lower-fanout-c", "0"),
    stable_uuid("segment", "bq-pmid-u1-lower-fanout-c", "1"),
    stable_uuid("segment", "bq-pmid-lower-back-route-c", "0"),
    stable_uuid("segment", "bq-pmid-lower-back-route-c", "1"),
    stable_uuid("via", "bq-pmid-u1-lower-via-c"),
    stable_uuid("via", "bq-pmid-capbus-via-c"),
    stable_uuid("segment", "bq-vbus-u1-to-q3-fanout-a", "0"),
    stable_uuid("segment", "bq-vbus-u1-to-q3-fanout-a", "1"),
    stable_uuid("segment", "bq-vbus-u1-to-q3-internal-a", "0"),
    stable_uuid("segment", "bq-vbus-u1-to-q3-internal-a", "1"),
    stable_uuid("via", "bq-vbus-u1-fanout-via-a"),
    stable_uuid("segment", "usb-vbus-raw-xiao-to-q3-service-edge-c", "0"),
    stable_uuid("segment", "usb-vbus-raw-xiao-to-q3-service-edge-c", "1"),
    stable_uuid("segment", "usb-vbus-raw-xiao-to-q3-service-edge-c", "2"),
    stable_uuid("via", "usb-vbus-raw-q3-pad-via-c"),
    stable_uuid("segment", "usb-vbus-raw-mod1-to-q3-top-edge-d", "0"),
    stable_uuid("segment", "usb-vbus-raw-mod1-to-q3-top-edge-d", "1"),
    stable_uuid("segment", "usb-vbus-raw-mod1-to-q3-top-edge-d", "2"),
    stable_uuid("segment", "usb-vbus-raw-mod1-to-q3-top-edge-d", "3"),
    stable_uuid("segment", "usb-vbus-raw-mod1-fanout-e", "0"),
    stable_uuid("segment", "usb-vbus-raw-bottom-edge-e", "0"),
    stable_uuid("segment", "usb-vbus-raw-bottom-edge-e", "1"),
    stable_uuid("segment", "usb-vbus-raw-bottom-edge-e", "2"),
    stable_uuid("segment", "usb-vbus-raw-q3-entry-e", "0"),
    stable_uuid("via", "usb-vbus-raw-mod1-via-e"),
    stable_uuid("via", "usb-vbus-raw-q3-via-e"),
    stable_uuid("segment", "usb-vbus-raw-u1-fanout-f", "0"),
    stable_uuid("segment", "usb-vbus-raw-q3-to-u1-bottom-f", "0"),
    stable_uuid("segment", "usb-vbus-raw-q3-to-u1-bottom-f", "1"),
    stable_uuid("segment", "usb-vbus-raw-q3-to-u1-bottom-f", "2"),
    stable_uuid("segment", "usb-vbus-raw-q3-entry-f", "0"),
    stable_uuid("via", "usb-vbus-raw-u1-via-f"),
    stable_uuid("via", "usb-vbus-raw-q3-via-f"),
    stable_uuid("segment", "usb-vbus-raw-u1-to-q3-top-g", "0"),
    stable_uuid("segment", "usb-vbus-raw-u1-to-q3-top-g", "1"),
    stable_uuid("segment", "usb-vbus-raw-u1-to-q3-top-g", "2"),
    stable_uuid("segment", "usb-vbus-raw-u1-to-q3-top-g", "3"),
    stable_uuid("segment", "usb-vbus-raw-u1-to-q3-top-g", "4"),
    stable_uuid("segment", "usb-vbus-raw-u1-to-q3-trial-u", "0"),
    stable_uuid("segment", "usb-vbus-raw-u1-to-q3-trial-u", "1"),
    stable_uuid("segment", "usb-vbus-raw-u1-to-q3-trial-u", "2"),
    stable_uuid("segment", "usb-vbus-raw-u1-to-q3-trial-u", "3"),
    stable_uuid("segment", "usb-vbus-raw-u1-fanout-u", "0"),
    stable_uuid("via", "usb-vbus-raw-u1-via-u"),
    stable_uuid("via", "usb-vbus-raw-q3-via-u"),
    stable_uuid("segment", "bq-vbus-q3-to-u1-b", "0"),
    stable_uuid("segment", "bq-vbus-q3-to-u1-b", "1"),
    stable_uuid("segment", "bq-vbus-q3-to-u1-b", "2"),
    stable_uuid("segment", "bq-vbus-u1-entry-b", "0"),
    stable_uuid("via", "bq-vbus-u1-entry-via-b"),
    stable_uuid("segment", "bq-vbus-u1-fanout-c", "0"),
    stable_uuid("segment", "bq-vbus-cap-bank-to-u1-c", "0"),
    stable_uuid("segment", "bq-vbus-cap-bank-to-u1-c", "1"),
    stable_uuid("segment", "bq-vbus-cap-bank-to-u1-c", "2"),
    stable_uuid("via", "bq-vbus-u1-fanout-via-c"),
    stable_uuid("segment", "bq-vbus-u1-to-capbank-w", "0"),
    stable_uuid("segment", "bq-vbus-u1-to-capbank-w", "1"),
    stable_uuid("segment", "bq-vbus-u1-to-capbank-w", "2"),
    stable_uuid("segment", "bq-vbus-u1-to-capbank-w", "3"),
    stable_uuid("segment", "bq-vbus-u1-q3-fanout-s", "0"),
    stable_uuid("segment", "bq-vbus-u1-q3-internal-s", "0"),
    stable_uuid("segment", "bq-vbus-u1-q3-internal-s", "1"),
    stable_uuid("segment", "bq-vbus-u1-q3-internal-s", "2"),
    stable_uuid("via", "bq-vbus-u1-q3-via-s"),
    stable_uuid("segment", "bq-vbus-u1-q3-fanout-t", "0"),
    stable_uuid("segment", "bq-vbus-u1-q3-bottom-t", "0"),
    stable_uuid("segment", "bq-vbus-u1-q3-bottom-t", "1"),
    stable_uuid("segment", "bq-vbus-u1-q3-bottom-t", "2"),
    stable_uuid("via", "bq-vbus-u1-q3-u1-via-t"),
    stable_uuid("via", "bq-vbus-u1-q3-join-via-t"),
    stable_uuid("segment", "boost-vcc-u3-fanout-b", "0"),
    stable_uuid("segment", "boost-vcc-internal-route-b", "0"),
    stable_uuid("segment", "boost-vcc-internal-route-b", "1"),
    stable_uuid("segment", "boost-vcc-internal-route-b", "2"),
    stable_uuid("via", "boost-vcc-u3-via-b"),
    stable_uuid("via", "boost-vcc-c405-via-b"),
    stable_uuid("segment", "uv-node-u4-fanout", "0"),
    stable_uuid("segment", "uv-node-bottom-route", "0"),
    stable_uuid("segment", "uv-node-bottom-route", "1"),
    stable_uuid("segment", "uv-node-bottom-route", "2"),
    stable_uuid("via", "uv-node-u4-via"),
    stable_uuid("via", "uv-node-divider-via"),
}


def generated_uuids() -> set[str]:
    ids: set[str] = set()
    for route in SEGMENTS:
        points = route["points"]
        for index in range(len(points) - 1):
            ids.add(stable_uuid("segment", str(route["name"]), str(index)))
    for via in VIAS:
        ids.add(stable_uuid("via", str(via["name"])))
    ids.update(uuid for _, _, uuid in GROUND_ZONES)
    ids.add(stable_uuid("zone", "q1-solar-protected-join"))
    ids.add(stable_uuid("zone", "q3-bq-vbus-join"))
    ids.update(RETIRED_GENERATED_UUIDS)
    return ids


def remove_generated_routes(text: str) -> str:
    ids = generated_uuids()
    result: list[str] = []
    idx = 0
    pattern = re.compile(r"\n[ \t]*\((segment|via|zone)\b")
    while True:
        match = pattern.search(text, idx)
        if not match:
            result.append(text[idx:])
            break
        start = match.start()
        result.append(text[idx:start])
        depth = 0
        end = start + 1
        while end < len(text):
            char = text[end]
            if char == "(":
                depth += 1
            elif char == ")":
                depth -= 1
                if depth == 0:
                    end += 1
                    break
            end += 1
        block = text[start:end]
        uuid_match = re.search(r'\(uuid "([^"]+)"\)', block)
        if not uuid_match or uuid_match.group(1) not in ids:
            result.append(block)
        idx = end
    return "".join(result)


def segment_block(name: str, index: int, net: str, layer: str, width: float, start: tuple[float, float], end: tuple[float, float]) -> str:
    return (
        f'  (segment\n'
        f'    (start {start[0]:.2f} {start[1]:.2f})\n'
        f'    (end {end[0]:.2f} {end[1]:.2f})\n'
        f'    (width {width:.2f})\n'
        f'    (layer "{layer}")\n'
        f'    (net "{net}")\n'
        f'    (uuid "{stable_uuid("segment", name, str(index))}")\n'
        f'  )'
    )


def via_block(name: str, net: str, at: tuple[float, float], size: float = 0.60, drill: float = 0.30) -> str:
    return (
        f'  (via\n'
        f'    (at {at[0]:.2f} {at[1]:.2f})\n'
        f'    (size {size:.2f})\n'
        f'    (drill {drill:.2f})\n'
        f'    (layers "F.Cu" "B.Cu")\n'
        f'    (net "{net}")\n'
        f'    (uuid "{stable_uuid("via", name)}")\n'
        f'  )'
    )


def ground_zone_block(layer: str, name: str, zone_uuid: str) -> str:
    return (
        f'  (zone\n'
        f'    (net 1)\n'
        f'    (net_name "GND")\n'
        f'    (layer "{layer}")\n'
        f'    (uuid "{zone_uuid}")\n'
        f'    (name "{name}")\n'
        f'    (hatch edge 0.50)\n'
        f'    (connect_pads\n'
        f'      (clearance 0.15)\n'
        f'    )\n'
        f'    (min_thickness 0.20)\n'
        f'    (filled_areas_thickness no)\n'
        f'    (fill\n'
        f'      (thermal_gap 0.50)\n'
        f'      (thermal_bridge_width 0.50)\n'
        f'    )\n'
        f'    (polygon\n'
        f'      (pts\n'
        f'        (xy 15.50 15.50) (xy 111.50 15.50) (xy 111.50 101.50) (xy 15.50 101.50)\n'
        f'      )\n'
        f'    )\n'
        f'  )'
    )


def generated_blocks() -> str:
    blocks: list[str] = []
    for route in SEGMENTS:
        points = route["points"]
        for index, (start, end) in enumerate(zip(points, points[1:])):
            blocks.append(
                segment_block(
                    str(route["name"]),
                    index,
                    str(route["net"]),
                    str(route["layer"]),
                    float(route["width"]),
                    start,  # type: ignore[arg-type]
                    end,  # type: ignore[arg-type]
                )
            )
    for via in VIAS:
        blocks.append(
            via_block(
                str(via["name"]),
                str(via["net"]),
                via["at"],  # type: ignore[arg-type]
                float(via.get("size", 0.60)),
                float(via.get("drill", 0.30)),
            )
        )
    for layer, name, zone_uuid in GROUND_ZONES:
        blocks.append(ground_zone_block(layer, name, zone_uuid))
    return "\n".join(blocks)


def main() -> None:
    text = remove_generated_routes(PCB.read_text(encoding="utf-8")).rstrip()
    if not text.endswith(")"):
        raise SystemExit("PCB file does not end with a closing S-expression")
    body = text[:-1].rstrip()
    PCB.write_text(f"{body}\n{generated_blocks()}\n)\n", encoding="utf-8")
    print("Generated initial routes, E22 control/SPI/VCC, TPS61088 local output/SW pins, charge LED/STAT, temp/UV/OV-divider, U1/U2/Q-gate/MOSFET-drain local links and top/L2 ground pours")


if __name__ == "__main__":
    main()
